/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zashigaofa.client.model.PresetPayToolInfo;
import com.zashigaofa.client.model.RefundChargeInfo;
import com.zashigaofa.client.model.TradeFundBill;
import com.zashigaofa.client.model.VoucherDetail;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for AlipayTradeRefundResponse
 */
class AlipayTradeRefundResponseTest {
    private final AlipayTradeRefundResponse model = new AlipayTradeRefundResponse();

    /**
     * Model tests for AlipayTradeRefundResponse
     */
    @Test
    void testAlipayTradeRefundResponse() {
        // TODO: test AlipayTradeRefundResponse
    }

    /**
     * Test the property 'code'
     */
    @Test
    void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'msg'
     */
    @Test
    void msgTest() {
        // TODO: test msg
    }

    /**
     * Test the property 'subCode'
     */
    @Test
    void subCodeTest() {
        // TODO: test subCode
    }

    /**
     * Test the property 'subMsg'
     */
    @Test
    void subMsgTest() {
        // TODO: test subMsg
    }

    /**
     * Test the property 'body'
     */
    @Test
    void bodyTest() {
        // TODO: test body
    }

    /**
     * Test the property 'isError'
     */
    @Test
    void isErrorTest() {
        // TODO: test isError
    }

    /**
     * Test the property 'buyerLogonId'
     */
    @Test
    void buyerLogonIdTest() {
        // TODO: test buyerLogonId
    }

    /**
     * Test the property 'buyerOpenId'
     */
    @Test
    void buyerOpenIdTest() {
        // TODO: test buyerOpenId
    }

    /**
     * Test the property 'buyerUserId'
     */
    @Test
    void buyerUserIdTest() {
        // TODO: test buyerUserId
    }

    /**
     * Test the property 'fundChange'
     */
    @Test
    void fundChangeTest() {
        // TODO: test fundChange
    }

    /**
     * Test the property 'gmtRefundPay'
     */
    @Test
    void gmtRefundPayTest() {
        // TODO: test gmtRefundPay
    }

    /**
     * Test the property 'hasDepositBack'
     */
    @Test
    void hasDepositBackTest() {
        // TODO: test hasDepositBack
    }

    /**
     * Test the property 'openId'
     */
    @Test
    void openIdTest() {
        // TODO: test openId
    }

    /**
     * Test the property 'outTradeNo'
     */
    @Test
    void outTradeNoTest() {
        // TODO: test outTradeNo
    }

    /**
     * Test the property 'preAuthCancelFee'
     */
    @Test
    void preAuthCancelFeeTest() {
        // TODO: test preAuthCancelFee
    }

    /**
     * Test the property 'presentRefundBuyerAmount'
     */
    @Test
    void presentRefundBuyerAmountTest() {
        // TODO: test presentRefundBuyerAmount
    }

    /**
     * Test the property 'presentRefundDiscountAmount'
     */
    @Test
    void presentRefundDiscountAmountTest() {
        // TODO: test presentRefundDiscountAmount
    }

    /**
     * Test the property 'presentRefundMdiscountAmount'
     */
    @Test
    void presentRefundMdiscountAmountTest() {
        // TODO: test presentRefundMdiscountAmount
    }

    /**
     * Test the property 'refundChargeAmount'
     */
    @Test
    void refundChargeAmountTest() {
        // TODO: test refundChargeAmount
    }

    /**
     * Test the property 'refundChargeInfoList'
     */
    @Test
    void refundChargeInfoListTest() {
        // TODO: test refundChargeInfoList
    }

    /**
     * Test the property 'refundCurrency'
     */
    @Test
    void refundCurrencyTest() {
        // TODO: test refundCurrency
    }

    /**
     * Test the property 'refundDetailItemList'
     */
    @Test
    void refundDetailItemListTest() {
        // TODO: test refundDetailItemList
    }

    /**
     * Test the property 'refundFee'
     */
    @Test
    void refundFeeTest() {
        // TODO: test refundFee
    }

    /**
     * Test the property 'refundHybAmount'
     */
    @Test
    void refundHybAmountTest() {
        // TODO: test refundHybAmount
    }

    /**
     * Test the property 'refundPresetPaytoolList'
     */
    @Test
    void refundPresetPaytoolListTest() {
        // TODO: test refundPresetPaytoolList
    }

    /**
     * Test the property 'refundSettlementId'
     */
    @Test
    void refundSettlementIdTest() {
        // TODO: test refundSettlementId
    }

    /**
     * Test the property 'refundVoucherDetailList'
     */
    @Test
    void refundVoucherDetailListTest() {
        // TODO: test refundVoucherDetailList
    }

    /**
     * Test the property 'sendBackFee'
     */
    @Test
    void sendBackFeeTest() {
        // TODO: test sendBackFee
    }

    /**
     * Test the property 'storeName'
     */
    @Test
    void storeNameTest() {
        // TODO: test storeName
    }

    /**
     * Test the property 'tradeNo'
     */
    @Test
    void tradeNoTest() {
        // TODO: test tradeNo
    }

}
