/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zashigaofa.client.model.SubFee;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ChargeInfo
 */
class ChargeInfoTest {
    private final ChargeInfo model = new ChargeInfo();

    /**
     * Model tests for ChargeInfo
     */
    @Test
    void testChargeInfo() {
        // TODO: test ChargeInfo
    }

    /**
     * Test the property 'chargeFee'
     */
    @Test
    void chargeFeeTest() {
        // TODO: test chargeFee
    }

    /**
     * Test the property 'chargeType'
     */
    @Test
    void chargeTypeTest() {
        // TODO: test chargeType
    }

    /**
     * Test the property 'isRatingOnSwitch'
     */
    @Test
    void isRatingOnSwitchTest() {
        // TODO: test isRatingOnSwitch
    }

    /**
     * Test the property 'isRatingOnTradeReceiver'
     */
    @Test
    void isRatingOnTradeReceiverTest() {
        // TODO: test isRatingOnTradeReceiver
    }

    /**
     * Test the property 'originalChargeFee'
     */
    @Test
    void originalChargeFeeTest() {
        // TODO: test originalChargeFee
    }

    /**
     * Test the property 'subFeeDetailList'
     */
    @Test
    void subFeeDetailListTest() {
        // TODO: test subFeeDetailList
    }

    /**
     * Test the property 'switchFeeRate'
     */
    @Test
    void switchFeeRateTest() {
        // TODO: test switchFeeRate
    }

}
