/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zashigaofa.client.model.DirectoryItem;
import com.zashigaofa.client.model.FileItem;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for FileListResult
 */
class FileListResultTest {
    private final FileListResult model = new FileListResult();

    /**
     * Model tests for FileListResult
     */
    @Test
    void testFileListResult() {
        // TODO: test FileListResult
    }

    /**
     * Test the property 'directories'
     */
    @Test
    void directoriesTest() {
        // TODO: test directories
    }

    /**
     * Test the property 'files'
     */
    @Test
    void filesTest() {
        // TODO: test files
    }

    /**
     * Test the property 'totalDirectories'
     */
    @Test
    void totalDirectoriesTest() {
        // TODO: test totalDirectories
    }

    /**
     * Test the property 'totalFiles'
     */
    @Test
    void totalFilesTest() {
        // TODO: test totalFiles
    }

    /**
     * Test the property 'size'
     */
    @Test
    void sizeTest() {
        // TODO: test size
    }

}
