/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for GeoLocationResponseModel
 */
class GeoLocationResponseModelTest {
    private final GeoLocationResponseModel model = new GeoLocationResponseModel();

    /**
     * Model tests for GeoLocationResponseModel
     */
    @Test
    void testGeoLocationResponseModel() {
        // TODO: test GeoLocationResponseModel
    }

    /**
     * Test the property 'locationName'
     */
    @Test
    void locationNameTest() {
        // TODO: test locationName
    }

    /**
     * Test the property 'latitude'
     */
    @Test
    void latitudeTest() {
        // TODO: test latitude
    }

    /**
     * Test the property 'longitude'
     */
    @Test
    void longitudeTest() {
        // TODO: test longitude
    }

    /**
     * Test the property 'locationType'
     */
    @Test
    void locationTypeTest() {
        // TODO: test locationType
    }

    /**
     * Test the property 'recipientName'
     */
    @Test
    void recipientNameTest() {
        // TODO: test recipientName
    }

    /**
     * Test the property 'phoneNumber'
     */
    @Test
    void phoneNumberTest() {
        // TODO: test phoneNumber
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'country'
     */
    @Test
    void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'state'
     */
    @Test
    void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'city'
     */
    @Test
    void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'district'
     */
    @Test
    void districtTest() {
        // TODO: test district
    }

    /**
     * Test the property 'street'
     */
    @Test
    void streetTest() {
        // TODO: test street
    }

    /**
     * Test the property 'zipCode'
     */
    @Test
    void zipCodeTest() {
        // TODO: test zipCode
    }

    /**
     * Test the property 'address'
     */
    @Test
    void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'mapType'
     */
    @Test
    void mapTypeTest() {
        // TODO: test mapType
    }

    /**
     * Test the property 'remark'
     */
    @Test
    void remarkTest() {
        // TODO: test remark
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'enable'
     */
    @Test
    void enableTest() {
        // TODO: test enable
    }

    /**
     * Test the property 'showIndex'
     */
    @Test
    void showIndexTest() {
        // TODO: test showIndex
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'lastUpdate'
     */
    @Test
    void lastUpdateTest() {
        // TODO: test lastUpdate
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

}
