/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ListResponseItem
 */
class ListResponseItemTest {
    private final ListResponseItem model = new ListResponseItem();

    /**
     * Model tests for ListResponseItem
     */
    @Test
    void testListResponseItem() {
        // TODO: test ListResponseItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'userID'
     */
    @Test
    void userIDTest() {
        // TODO: test userID
    }

    /**
     * Test the property 'userName'
     */
    @Test
    void userNameTest() {
        // TODO: test userName
    }

    /**
     * Test the property 'nickName'
     */
    @Test
    void nickNameTest() {
        // TODO: test nickName
    }

    /**
     * Test the property 'avatar'
     */
    @Test
    void avatarTest() {
        // TODO: test avatar
    }

    /**
     * Test the property 'email'
     */
    @Test
    void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'phone'
     */
    @Test
    void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'role'
     */
    @Test
    void roleTest() {
        // TODO: test role
    }

    /**
     * Test the property 'permission'
     */
    @Test
    void permissionTest() {
        // TODO: test permission
    }

    /**
     * Test the property 'lastUpdate'
     */
    @Test
    void lastUpdateTest() {
        // TODO: test lastUpdate
    }

}
