/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OAuthAccountBindRequest
 */
class OAuthAccountBindRequestTest {
    private final OAuthAccountBindRequest model = new OAuthAccountBindRequest();

    /**
     * Model tests for OAuthAccountBindRequest
     */
    @Test
    void testOAuthAccountBindRequest() {
        // TODO: test OAuthAccountBindRequest
    }

    /**
     * Test the property 'unionID'
     */
    @Test
    void unionIDTest() {
        // TODO: test unionID
    }

    /**
     * Test the property 'platform'
     */
    @Test
    void platformTest() {
        // TODO: test platform
    }

    /**
     * Test the property 'platformName'
     */
    @Test
    void platformNameTest() {
        // TODO: test platformName
    }

    /**
     * Test the property 'avatar'
     */
    @Test
    void avatarTest() {
        // TODO: test avatar
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

}
