/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Order
 */
class OrderTest {
    private final Order model = new Order();

    /**
     * Model tests for Order
     */
    @Test
    void testOrder() {
        // TODO: test Order
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'userID'
     */
    @Test
    void userIDTest() {
        // TODO: test userID
    }

    /**
     * Test the property 'payType'
     */
    @Test
    void payTypeTest() {
        // TODO: test payType
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'orderNo'
     */
    @Test
    void orderNoTest() {
        // TODO: test orderNo
    }

    /**
     * Test the property 'tradeNo'
     */
    @Test
    void tradeNoTest() {
        // TODO: test tradeNo
    }

    /**
     * Test the property 'status'
     */
    @Test
    void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'productType'
     */
    @Test
    void productTypeTest() {
        // TODO: test productType
    }

    /**
     * Test the property 'productID'
     */
    @Test
    void productIDTest() {
        // TODO: test productID
    }

    /**
     * Test the property 'productName'
     */
    @Test
    void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'allowRefund'
     */
    @Test
    void allowRefundTest() {
        // TODO: test allowRefund
    }

    /**
     * Test the property 'allowRefundUntil'
     */
    @Test
    void allowRefundUntilTest() {
        // TODO: test allowRefundUntil
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'remark'
     */
    @Test
    void remarkTest() {
        // TODO: test remark
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'orderPayTime'
     */
    @Test
    void orderPayTimeTest() {
        // TODO: test orderPayTime
    }

    /**
     * Test the property 'expireTime'
     */
    @Test
    void expireTimeTest() {
        // TODO: test expireTime
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'lastUpdate'
     */
    @Test
    void lastUpdateTest() {
        // TODO: test lastUpdate
    }

}
