/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zashigaofa.client.model.RefundSubFee;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for RefundChargeInfo
 */
class RefundChargeInfoTest {
    private final RefundChargeInfo model = new RefundChargeInfo();

    /**
     * Model tests for RefundChargeInfo
     */
    @Test
    void testRefundChargeInfo() {
        // TODO: test RefundChargeInfo
    }

    /**
     * Test the property 'chargeType'
     */
    @Test
    void chargeTypeTest() {
        // TODO: test chargeType
    }

    /**
     * Test the property 'refundChargeFee'
     */
    @Test
    void refundChargeFeeTest() {
        // TODO: test refundChargeFee
    }

    /**
     * Test the property 'refundSubFeeDetailList'
     */
    @Test
    void refundSubFeeDetailListTest() {
        // TODO: test refundSubFeeDetailList
    }

    /**
     * Test the property 'switchFeeRate'
     */
    @Test
    void switchFeeRateTest() {
        // TODO: test switchFeeRate
    }

}
