/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Settings
 */
class SettingsTest {
    private final Settings model = new Settings();

    /**
     * Model tests for Settings
     */
    @Test
    void testSettings() {
        // TODO: test Settings
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'bizCode'
     */
    @Test
    void bizCodeTest() {
        // TODO: test bizCode
    }

    /**
     * Test the property 'bizIdentity'
     */
    @Test
    void bizIdentityTest() {
        // TODO: test bizIdentity
    }

    /**
     * Test the property 'providerCode'
     */
    @Test
    void providerCodeTest() {
        // TODO: test providerCode
    }

    /**
     * Test the property 'groupCode'
     */
    @Test
    void groupCodeTest() {
        // TODO: test groupCode
    }

    /**
     * Test the property 'code'
     */
    @Test
    void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'value'
     */
    @Test
    void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'tags'
     */
    @Test
    void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'frontendUsable'
     */
    @Test
    void frontendUsableTest() {
        // TODO: test frontendUsable
    }

    /**
     * Test the property 'createDate'
     */
    @Test
    void createDateTest() {
        // TODO: test createDate
    }

    /**
     * Test the property 'lastUpdate'
     */
    @Test
    void lastUpdateTest() {
        // TODO: test lastUpdate
    }

}
