/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for TradeFundBill
 */
class TradeFundBillTest {
    private final TradeFundBill model = new TradeFundBill();

    /**
     * Model tests for TradeFundBill
     */
    @Test
    void testTradeFundBill() {
        // TODO: test TradeFundBill
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'bankCode'
     */
    @Test
    void bankCodeTest() {
        // TODO: test bankCode
    }

    /**
     * Test the property 'fundChannel'
     */
    @Test
    void fundChannelTest() {
        // TODO: test fundChannel
    }

    /**
     * Test the property 'fundType'
     */
    @Test
    void fundTypeTest() {
        // TODO: test fundType
    }

    /**
     * Test the property 'realAmount'
     */
    @Test
    void realAmountTest() {
        // TODO: test realAmount
    }

}
