/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateProfileRequest
 */
class UpdateProfileRequestTest {
    private final UpdateProfileRequest model = new UpdateProfileRequest();

    /**
     * Model tests for UpdateProfileRequest
     */
    @Test
    void testUpdateProfileRequest() {
        // TODO: test UpdateProfileRequest
    }

    /**
     * Test the property 'avatar'
     */
    @Test
    void avatarTest() {
        // TODO: test avatar
    }

    /**
     * Test the property 'data'
     */
    @Test
    void dataTest() {
        // TODO: test data
    }

    /**
     * Test the property 'nickName'
     */
    @Test
    void nickNameTest() {
        // TODO: test nickName
    }

    /**
     * Test the property 'interestTags'
     */
    @Test
    void interestTagsTest() {
        // TODO: test interestTags
    }

    /**
     * Test the property 'biography'
     */
    @Test
    void biographyTest() {
        // TODO: test biography
    }

    /**
     * Test the property 'gender'
     */
    @Test
    void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'birthday'
     */
    @Test
    void birthdayTest() {
        // TODO: test birthday
    }

    /**
     * Test the property 'occupation'
     */
    @Test
    void occupationTest() {
        // TODO: test occupation
    }

    /**
     * Test the property 'education'
     */
    @Test
    void educationTest() {
        // TODO: test education
    }

    /**
     * Test the property 'contact'
     */
    @Test
    void contactTest() {
        // TODO: test contact
    }

    /**
     * Test the property 'languages'
     */
    @Test
    void languagesTest() {
        // TODO: test languages
    }

    /**
     * Test the property 'socialLinks'
     */
    @Test
    void socialLinksTest() {
        // TODO: test socialLinks
    }

    /**
     * Test the property 'relationshipStatus'
     */
    @Test
    void relationshipStatusTest() {
        // TODO: test relationshipStatus
    }

    /**
     * Test the property 'company'
     */
    @Test
    void companyTest() {
        // TODO: test company
    }

    /**
     * Test the property 'industry'
     */
    @Test
    void industryTest() {
        // TODO: test industry
    }

    /**
     * Test the property 'companyPosition'
     */
    @Test
    void companyPositionTest() {
        // TODO: test companyPosition
    }

    /**
     * Test the property 'privateSettings'
     */
    @Test
    void privateSettingsTest() {
        // TODO: test privateSettings
    }

    /**
     * Test the property 'enable2FAAuth'
     */
    @Test
    void enable2FAAuthTest() {
        // TODO: test enable2FAAuth
    }

    /**
     * Test the property 'enableUserNameSignIn'
     */
    @Test
    void enableUserNameSignInTest() {
        // TODO: test enableUserNameSignIn
    }

    /**
     * Test the property 'enableEmailSignIn'
     */
    @Test
    void enableEmailSignInTest() {
        // TODO: test enableEmailSignIn
    }

    /**
     * Test the property 'enablePhoneSignIn'
     */
    @Test
    void enablePhoneSignInTest() {
        // TODO: test enablePhoneSignIn
    }

    /**
     * Test the property 'enableUnionIDSignIn'
     */
    @Test
    void enableUnionIDSignInTest() {
        // TODO: test enableUnionIDSignIn
    }

    /**
     * Test the property 'enableOAuth'
     */
    @Test
    void enableOAuthTest() {
        // TODO: test enableOAuth
    }

}
