/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zashigaofa.client.ApiClient;
/**
 * AppCheckVersionResult
 */
@JsonPropertyOrder({
  AppCheckVersionResult.JSON_PROPERTY_VERSIONS,
  AppCheckVersionResult.JSON_PROPERTY_NEW_VERSIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-31T07:56:41.646456145Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class AppCheckVersionResult {
  public static final String JSON_PROPERTY_VERSIONS = "versions";
  private JsonNullable<List<String>> versions = JsonNullable.<List<String>>undefined();

  public static final String JSON_PROPERTY_NEW_VERSIONS = "newVersions";
  private JsonNullable<List<String>> newVersions = JsonNullable.<List<String>>undefined();

  public AppCheckVersionResult() { 
  }

  public AppCheckVersionResult versions(@javax.annotation.Nullable List<String> versions) {
    this.versions = JsonNullable.<List<String>>of(versions);
    return this;
  }

  public AppCheckVersionResult addVersionsItem(String versionsItem) {
    if (this.versions == null || !this.versions.isPresent()) {
      this.versions = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.versions.get().add(versionsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get versions
   * @return versions
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public List<String> getVersions() {
        return versions.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VERSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getVersions_JsonNullable() {
    return versions;
  }
  
  @JsonProperty(JSON_PROPERTY_VERSIONS)
  public void setVersions_JsonNullable(JsonNullable<List<String>> versions) {
    this.versions = versions;
  }

  public void setVersions(@javax.annotation.Nullable List<String> versions) {
    this.versions = JsonNullable.<List<String>>of(versions);
  }


  public AppCheckVersionResult newVersions(@javax.annotation.Nullable List<String> newVersions) {
    this.newVersions = JsonNullable.<List<String>>of(newVersions);
    return this;
  }

  public AppCheckVersionResult addNewVersionsItem(String newVersionsItem) {
    if (this.newVersions == null || !this.newVersions.isPresent()) {
      this.newVersions = JsonNullable.<List<String>>of(new ArrayList<>());
    }
    try {
      this.newVersions.get().add(newVersionsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get newVersions
   * @return newVersions
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public List<String> getNewVersions() {
        return newVersions.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NEW_VERSIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<String>> getNewVersions_JsonNullable() {
    return newVersions;
  }
  
  @JsonProperty(JSON_PROPERTY_NEW_VERSIONS)
  public void setNewVersions_JsonNullable(JsonNullable<List<String>> newVersions) {
    this.newVersions = newVersions;
  }

  public void setNewVersions(@javax.annotation.Nullable List<String> newVersions) {
    this.newVersions = JsonNullable.<List<String>>of(newVersions);
  }


  /**
   * Return true if this AppCheckVersionResult object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AppCheckVersionResult appCheckVersionResult = (AppCheckVersionResult) o;
    return equalsNullable(this.versions, appCheckVersionResult.versions) &&
        equalsNullable(this.newVersions, appCheckVersionResult.newVersions);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(versions), hashCodeNullable(newVersions));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AppCheckVersionResult {\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("    newVersions: ").append(toIndentedString(newVersions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `versions` to the URL query string
    if (getVersions() != null) {
      for (int i = 0; i < getVersions().size(); i++) {
        joiner.add(String.format("%sversions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getVersions().get(i)))));
      }
    }

    // add `newVersions` to the URL query string
    if (getNewVersions() != null) {
      for (int i = 0; i < getNewVersions().size(); i++) {
        joiner.add(String.format("%snewVersions%s%s=%s", prefix, suffix,
            "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix),
            ApiClient.urlEncode(ApiClient.valueToString(getNewVersions().get(i)))));
      }
    }

    return joiner.toString();
  }
}

