/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zashigaofa.client.ApiClient;
/**
 * EmailSignInRequest
 */
@JsonPropertyOrder({
  EmailSignInRequest.JSON_PROPERTY_EMAIL,
  EmailSignInRequest.JSON_PROPERTY_VERIFY_CODE,
  EmailSignInRequest.JSON_PROPERTY_TWO_FACTOR_CODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-10T08:59:39.754837544Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class EmailSignInRequest {
  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nonnull
  private String email;

  public static final String JSON_PROPERTY_VERIFY_CODE = "verifyCode";
  @javax.annotation.Nonnull
  private String verifyCode;

  public static final String JSON_PROPERTY_TWO_FACTOR_CODE = "twoFactorCode";
  private JsonNullable<String> twoFactorCode = JsonNullable.<String>undefined();

  public EmailSignInRequest() { 
  }

  public EmailSignInRequest email(@javax.annotation.Nonnull String email) {
    this.email = email;
    return this;
  }

  /**
   * 用户邮箱地址
   * @return email
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmail(@javax.annotation.Nonnull String email) {
    this.email = email;
  }


  public EmailSignInRequest verifyCode(@javax.annotation.Nonnull String verifyCode) {
    this.verifyCode = verifyCode;
    return this;
  }

  /**
   * 验证码，长度为4到8位的数字
   * @return verifyCode
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_VERIFY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getVerifyCode() {
    return verifyCode;
  }


  @JsonProperty(JSON_PROPERTY_VERIFY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVerifyCode(@javax.annotation.Nonnull String verifyCode) {
    this.verifyCode = verifyCode;
  }


  public EmailSignInRequest twoFactorCode(@javax.annotation.Nullable String twoFactorCode) {
    this.twoFactorCode = JsonNullable.<String>of(twoFactorCode);
    return this;
  }

  /**
   * 双因素认证代码，如果启用双因素认证登录，则必填
   * @return twoFactorCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getTwoFactorCode() {
        return twoFactorCode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TWO_FACTOR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTwoFactorCode_JsonNullable() {
    return twoFactorCode;
  }
  
  @JsonProperty(JSON_PROPERTY_TWO_FACTOR_CODE)
  public void setTwoFactorCode_JsonNullable(JsonNullable<String> twoFactorCode) {
    this.twoFactorCode = twoFactorCode;
  }

  public void setTwoFactorCode(@javax.annotation.Nullable String twoFactorCode) {
    this.twoFactorCode = JsonNullable.<String>of(twoFactorCode);
  }


  /**
   * Return true if this EmailSignInRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmailSignInRequest emailSignInRequest = (EmailSignInRequest) o;
    return Objects.equals(this.email, emailSignInRequest.email) &&
        Objects.equals(this.verifyCode, emailSignInRequest.verifyCode) &&
        equalsNullable(this.twoFactorCode, emailSignInRequest.twoFactorCode);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(email, verifyCode, hashCodeNullable(twoFactorCode));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmailSignInRequest {\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    verifyCode: ").append(toIndentedString(verifyCode)).append("\n");
    sb.append("    twoFactorCode: ").append(toIndentedString(twoFactorCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `email` to the URL query string
    if (getEmail() != null) {
      joiner.add(String.format("%semail%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEmail()))));
    }

    // add `verifyCode` to the URL query string
    if (getVerifyCode() != null) {
      joiner.add(String.format("%sverifyCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getVerifyCode()))));
    }

    // add `twoFactorCode` to the URL query string
    if (getTwoFactorCode() != null) {
      joiner.add(String.format("%stwoFactorCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTwoFactorCode()))));
    }

    return joiner.toString();
  }
}

