/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zashigaofa.client.ApiClient;
/**
 * ExchangeRatePutRequest
 */
@JsonPropertyOrder({
  ExchangeRatePutRequest.JSON_PROPERTY_TO_CURRENCY_CODE,
  ExchangeRatePutRequest.JSON_PROPERTY_EXCHANGE_RATE,
  ExchangeRatePutRequest.JSON_PROPERTY_DESCRIPTION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-22T08:55:19.994923193Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class ExchangeRatePutRequest {
  public static final String JSON_PROPERTY_TO_CURRENCY_CODE = "toCurrencyCode";
  private JsonNullable<String> toCurrencyCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EXCHANGE_RATE = "exchangeRate";
  @javax.annotation.Nullable
  private Long exchangeRate;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public ExchangeRatePutRequest() { 
  }

  public ExchangeRatePutRequest toCurrencyCode(@javax.annotation.Nullable String toCurrencyCode) {
    this.toCurrencyCode = JsonNullable.<String>of(toCurrencyCode);
    return this;
  }

  /**
   * Get toCurrencyCode
   * @return toCurrencyCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getToCurrencyCode() {
        return toCurrencyCode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TO_CURRENCY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getToCurrencyCode_JsonNullable() {
    return toCurrencyCode;
  }
  
  @JsonProperty(JSON_PROPERTY_TO_CURRENCY_CODE)
  public void setToCurrencyCode_JsonNullable(JsonNullable<String> toCurrencyCode) {
    this.toCurrencyCode = toCurrencyCode;
  }

  public void setToCurrencyCode(@javax.annotation.Nullable String toCurrencyCode) {
    this.toCurrencyCode = JsonNullable.<String>of(toCurrencyCode);
  }


  public ExchangeRatePutRequest exchangeRate(@javax.annotation.Nullable Long exchangeRate) {
    this.exchangeRate = exchangeRate;
    return this;
  }

  /**
   * Get exchangeRate
   * @return exchangeRate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXCHANGE_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getExchangeRate() {
    return exchangeRate;
  }


  @JsonProperty(JSON_PROPERTY_EXCHANGE_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExchangeRate(@javax.annotation.Nullable Long exchangeRate) {
    this.exchangeRate = exchangeRate;
  }


  public ExchangeRatePutRequest description(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  /**
   * Return true if this ExchangeRatePutRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExchangeRatePutRequest exchangeRatePutRequest = (ExchangeRatePutRequest) o;
    return equalsNullable(this.toCurrencyCode, exchangeRatePutRequest.toCurrencyCode) &&
        Objects.equals(this.exchangeRate, exchangeRatePutRequest.exchangeRate) &&
        equalsNullable(this.description, exchangeRatePutRequest.description);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(toCurrencyCode), exchangeRate, hashCodeNullable(description));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExchangeRatePutRequest {\n");
    sb.append("    toCurrencyCode: ").append(toIndentedString(toCurrencyCode)).append("\n");
    sb.append("    exchangeRate: ").append(toIndentedString(exchangeRate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `toCurrencyCode` to the URL query string
    if (getToCurrencyCode() != null) {
      joiner.add(String.format("%stoCurrencyCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getToCurrencyCode()))));
    }

    // add `exchangeRate` to the URL query string
    if (getExchangeRate() != null) {
      joiner.add(String.format("%sexchangeRate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExchangeRate()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    return joiner.toString();
  }
}

