/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zashigaofa.client.ApiClient;
/**
 * GrantRequest
 */
@JsonPropertyOrder({
  GrantRequest.JSON_PROPERTY_REDIRECT_URI,
  GrantRequest.JSON_PROPERTY_GRANT_TYPE,
  GrantRequest.JSON_PROPERTY_SCOPES,
  GrantRequest.JSON_PROPERTY_USER_NAME,
  GrantRequest.JSON_PROPERTY_PASSWORD,
  GrantRequest.JSON_PROPERTY_UNION_ID,
  GrantRequest.JSON_PROPERTY_PLATFORM,
  GrantRequest.JSON_PROPERTY_EXPIRE_IN_DAYS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-10T08:59:39.754837544Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class GrantRequest {
  public static final String JSON_PROPERTY_REDIRECT_URI = "redirect_uri";
  private JsonNullable<String> redirectUri = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_GRANT_TYPE = "grant_type";
  @javax.annotation.Nonnull
  private String grantType;

  public static final String JSON_PROPERTY_SCOPES = "scopes";
  @javax.annotation.Nonnull
  private String scopes;

  public static final String JSON_PROPERTY_USER_NAME = "userName";
  private JsonNullable<String> userName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PASSWORD = "password";
  private JsonNullable<String> password = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_UNION_ID = "unionId";
  private JsonNullable<String> unionId = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  private JsonNullable<String> platform = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_EXPIRE_IN_DAYS = "expireInDays";
  @javax.annotation.Nullable
  private Integer expireInDays;

  public GrantRequest() { 
  }

  public GrantRequest redirectUri(@javax.annotation.Nullable String redirectUri) {
    this.redirectUri = JsonNullable.<String>of(redirectUri);
    return this;
  }

  /**
   * 返回地址。默认无限制，也可在【安全-开放认证网址白名单】配置
   * @return redirectUri
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getRedirectUri() {
        return redirectUri.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_REDIRECT_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getRedirectUri_JsonNullable() {
    return redirectUri;
  }
  
  @JsonProperty(JSON_PROPERTY_REDIRECT_URI)
  public void setRedirectUri_JsonNullable(JsonNullable<String> redirectUri) {
    this.redirectUri = redirectUri;
  }

  public void setRedirectUri(@javax.annotation.Nullable String redirectUri) {
    this.redirectUri = JsonNullable.<String>of(redirectUri);
  }


  public GrantRequest grantType(@javax.annotation.Nonnull String grantType) {
    this.grantType = grantType;
    return this;
  }

  /**
   * 授权类型。可选：email、phone、unionid、account
   * @return grantType
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_GRANT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getGrantType() {
    return grantType;
  }


  @JsonProperty(JSON_PROPERTY_GRANT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setGrantType(@javax.annotation.Nonnull String grantType) {
    this.grantType = grantType;
  }


  public GrantRequest scopes(@javax.annotation.Nonnull String scopes) {
    this.scopes = scopes;
    return this;
  }

  /**
   * 自定义授权范围，用英文空格分隔
   * @return scopes
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SCOPES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getScopes() {
    return scopes;
  }


  @JsonProperty(JSON_PROPERTY_SCOPES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScopes(@javax.annotation.Nonnull String scopes) {
    this.scopes = scopes;
  }


  public GrantRequest userName(@javax.annotation.Nullable String userName) {
    this.userName = JsonNullable.<String>of(userName);
    return this;
  }

  /**
   * 用户名。授权类型为：email/phone/account必填
   * @return userName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getUserName() {
        return userName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_USER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUserName_JsonNullable() {
    return userName;
  }
  
  @JsonProperty(JSON_PROPERTY_USER_NAME)
  public void setUserName_JsonNullable(JsonNullable<String> userName) {
    this.userName = userName;
  }

  public void setUserName(@javax.annotation.Nullable String userName) {
    this.userName = JsonNullable.<String>of(userName);
  }


  public GrantRequest password(@javax.annotation.Nullable String password) {
    this.password = JsonNullable.<String>of(password);
    return this;
  }

  /**
   * 登录密码。授权类型为：email/phone/account必填
   * @return password
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPassword() {
        return password.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPassword_JsonNullable() {
    return password;
  }
  
  @JsonProperty(JSON_PROPERTY_PASSWORD)
  public void setPassword_JsonNullable(JsonNullable<String> password) {
    this.password = password;
  }

  public void setPassword(@javax.annotation.Nullable String password) {
    this.password = JsonNullable.<String>of(password);
  }


  public GrantRequest unionId(@javax.annotation.Nullable String unionId) {
    this.unionId = JsonNullable.<String>of(unionId);
    return this;
  }

  /**
   * unionId。授权类型为：unionid必填
   * @return unionId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getUnionId() {
        return unionId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_UNION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUnionId_JsonNullable() {
    return unionId;
  }
  
  @JsonProperty(JSON_PROPERTY_UNION_ID)
  public void setUnionId_JsonNullable(JsonNullable<String> unionId) {
    this.unionId = unionId;
  }

  public void setUnionId(@javax.annotation.Nullable String unionId) {
    this.unionId = JsonNullable.<String>of(unionId);
  }


  public GrantRequest platform(@javax.annotation.Nullable String platform) {
    this.platform = JsonNullable.<String>of(platform);
    return this;
  }

  /**
   * 平台。授权类型为：unionid必填
   * @return platform
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPlatform() {
        return platform.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPlatform_JsonNullable() {
    return platform;
  }
  
  @JsonProperty(JSON_PROPERTY_PLATFORM)
  public void setPlatform_JsonNullable(JsonNullable<String> platform) {
    this.platform = platform;
  }

  public void setPlatform(@javax.annotation.Nullable String platform) {
    this.platform = JsonNullable.<String>of(platform);
  }


  public GrantRequest expireInDays(@javax.annotation.Nullable Integer expireInDays) {
    this.expireInDays = expireInDays;
    return this;
  }

  /**
   * 授权有效期。1~99天
   * minimum: 1
   * maximum: 99
   * @return expireInDays
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRE_IN_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Integer getExpireInDays() {
    return expireInDays;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRE_IN_DAYS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpireInDays(@javax.annotation.Nullable Integer expireInDays) {
    this.expireInDays = expireInDays;
  }


  /**
   * Return true if this GrantRequest object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GrantRequest grantRequest = (GrantRequest) o;
    return equalsNullable(this.redirectUri, grantRequest.redirectUri) &&
        Objects.equals(this.grantType, grantRequest.grantType) &&
        Objects.equals(this.scopes, grantRequest.scopes) &&
        equalsNullable(this.userName, grantRequest.userName) &&
        equalsNullable(this.password, grantRequest.password) &&
        equalsNullable(this.unionId, grantRequest.unionId) &&
        equalsNullable(this.platform, grantRequest.platform) &&
        Objects.equals(this.expireInDays, grantRequest.expireInDays);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(redirectUri), grantType, scopes, hashCodeNullable(userName), hashCodeNullable(password), hashCodeNullable(unionId), hashCodeNullable(platform), expireInDays);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GrantRequest {\n");
    sb.append("    redirectUri: ").append(toIndentedString(redirectUri)).append("\n");
    sb.append("    grantType: ").append(toIndentedString(grantType)).append("\n");
    sb.append("    scopes: ").append(toIndentedString(scopes)).append("\n");
    sb.append("    userName: ").append(toIndentedString(userName)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    unionId: ").append(toIndentedString(unionId)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    expireInDays: ").append(toIndentedString(expireInDays)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `redirect_uri` to the URL query string
    if (getRedirectUri() != null) {
      joiner.add(String.format("%sredirect_uri%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getRedirectUri()))));
    }

    // add `grant_type` to the URL query string
    if (getGrantType() != null) {
      joiner.add(String.format("%sgrant_type%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGrantType()))));
    }

    // add `scopes` to the URL query string
    if (getScopes() != null) {
      joiner.add(String.format("%sscopes%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getScopes()))));
    }

    // add `userName` to the URL query string
    if (getUserName() != null) {
      joiner.add(String.format("%suserName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserName()))));
    }

    // add `password` to the URL query string
    if (getPassword() != null) {
      joiner.add(String.format("%spassword%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPassword()))));
    }

    // add `unionId` to the URL query string
    if (getUnionId() != null) {
      joiner.add(String.format("%sunionId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnionId()))));
    }

    // add `platform` to the URL query string
    if (getPlatform() != null) {
      joiner.add(String.format("%splatform%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatform()))));
    }

    // add `expireInDays` to the URL query string
    if (getExpireInDays() != null) {
      joiner.add(String.format("%sexpireInDays%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getExpireInDays()))));
    }

    return joiner.toString();
  }
}

