/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zashigaofa.client.ApiClient;
/**
 * IntactChargeInfo
 */
@JsonPropertyOrder({
  IntactChargeInfo.JSON_PROPERTY_ACTUAL_AMOUNT,
  IntactChargeInfo.JSON_PROPERTY_BILL_TYPE,
  IntactChargeInfo.JSON_PROPERTY_GMT_PAY,
  IntactChargeInfo.JSON_PROPERTY_IS_REFUND,
  IntactChargeInfo.JSON_PROPERTY_OUT_BIZ_NO,
  IntactChargeInfo.JSON_PROPERTY_PLAN_AMOUNT,
  IntactChargeInfo.JSON_PROPERTY_PRODUCT_NAME,
  IntactChargeInfo.JSON_PROPERTY_SERVICE_TARGET,
  IntactChargeInfo.JSON_PROPERTY_SERVICE_TYPE,
  IntactChargeInfo.JSON_PROPERTY_STATUS,
  IntactChargeInfo.JSON_PROPERTY_TARGET_ACCOUNT_NO,
  IntactChargeInfo.JSON_PROPERTY_TARGET_USER_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-10T08:59:39.754837544Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class IntactChargeInfo {
  public static final String JSON_PROPERTY_ACTUAL_AMOUNT = "actualAmount";
  private JsonNullable<String> actualAmount = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BILL_TYPE = "billType";
  private JsonNullable<String> billType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_GMT_PAY = "gmtPay";
  private JsonNullable<String> gmtPay = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_IS_REFUND = "isRefund";
  @javax.annotation.Nullable
  private Boolean isRefund;

  public static final String JSON_PROPERTY_OUT_BIZ_NO = "outBizNo";
  private JsonNullable<String> outBizNo = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PLAN_AMOUNT = "planAmount";
  private JsonNullable<String> planAmount = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PRODUCT_NAME = "productName";
  private JsonNullable<String> productName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SERVICE_TARGET = "serviceTarget";
  private JsonNullable<String> serviceTarget = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SERVICE_TYPE = "serviceType";
  private JsonNullable<String> serviceType = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_STATUS = "status";
  private JsonNullable<String> status = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TARGET_ACCOUNT_NO = "targetAccountNo";
  private JsonNullable<String> targetAccountNo = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TARGET_USER_ID = "targetUserId";
  private JsonNullable<String> targetUserId = JsonNullable.<String>undefined();

  public IntactChargeInfo() { 
  }

  public IntactChargeInfo actualAmount(@javax.annotation.Nullable String actualAmount) {
    this.actualAmount = JsonNullable.<String>of(actualAmount);
    return this;
  }

  /**
   * Get actualAmount
   * @return actualAmount
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getActualAmount() {
        return actualAmount.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_ACTUAL_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getActualAmount_JsonNullable() {
    return actualAmount;
  }
  
  @JsonProperty(JSON_PROPERTY_ACTUAL_AMOUNT)
  public void setActualAmount_JsonNullable(JsonNullable<String> actualAmount) {
    this.actualAmount = actualAmount;
  }

  public void setActualAmount(@javax.annotation.Nullable String actualAmount) {
    this.actualAmount = JsonNullable.<String>of(actualAmount);
  }


  public IntactChargeInfo billType(@javax.annotation.Nullable String billType) {
    this.billType = JsonNullable.<String>of(billType);
    return this;
  }

  /**
   * Get billType
   * @return billType
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getBillType() {
        return billType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BILL_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBillType_JsonNullable() {
    return billType;
  }
  
  @JsonProperty(JSON_PROPERTY_BILL_TYPE)
  public void setBillType_JsonNullable(JsonNullable<String> billType) {
    this.billType = billType;
  }

  public void setBillType(@javax.annotation.Nullable String billType) {
    this.billType = JsonNullable.<String>of(billType);
  }


  public IntactChargeInfo gmtPay(@javax.annotation.Nullable String gmtPay) {
    this.gmtPay = JsonNullable.<String>of(gmtPay);
    return this;
  }

  /**
   * Get gmtPay
   * @return gmtPay
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getGmtPay() {
        return gmtPay.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_GMT_PAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getGmtPay_JsonNullable() {
    return gmtPay;
  }
  
  @JsonProperty(JSON_PROPERTY_GMT_PAY)
  public void setGmtPay_JsonNullable(JsonNullable<String> gmtPay) {
    this.gmtPay = gmtPay;
  }

  public void setGmtPay(@javax.annotation.Nullable String gmtPay) {
    this.gmtPay = JsonNullable.<String>of(gmtPay);
  }


  public IntactChargeInfo isRefund(@javax.annotation.Nullable Boolean isRefund) {
    this.isRefund = isRefund;
    return this;
  }

  /**
   * Get isRefund
   * @return isRefund
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_REFUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsRefund() {
    return isRefund;
  }


  @JsonProperty(JSON_PROPERTY_IS_REFUND)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsRefund(@javax.annotation.Nullable Boolean isRefund) {
    this.isRefund = isRefund;
  }


  public IntactChargeInfo outBizNo(@javax.annotation.Nullable String outBizNo) {
    this.outBizNo = JsonNullable.<String>of(outBizNo);
    return this;
  }

  /**
   * Get outBizNo
   * @return outBizNo
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getOutBizNo() {
        return outBizNo.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OUT_BIZ_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getOutBizNo_JsonNullable() {
    return outBizNo;
  }
  
  @JsonProperty(JSON_PROPERTY_OUT_BIZ_NO)
  public void setOutBizNo_JsonNullable(JsonNullable<String> outBizNo) {
    this.outBizNo = outBizNo;
  }

  public void setOutBizNo(@javax.annotation.Nullable String outBizNo) {
    this.outBizNo = JsonNullable.<String>of(outBizNo);
  }


  public IntactChargeInfo planAmount(@javax.annotation.Nullable String planAmount) {
    this.planAmount = JsonNullable.<String>of(planAmount);
    return this;
  }

  /**
   * Get planAmount
   * @return planAmount
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPlanAmount() {
        return planAmount.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PLAN_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPlanAmount_JsonNullable() {
    return planAmount;
  }
  
  @JsonProperty(JSON_PROPERTY_PLAN_AMOUNT)
  public void setPlanAmount_JsonNullable(JsonNullable<String> planAmount) {
    this.planAmount = planAmount;
  }

  public void setPlanAmount(@javax.annotation.Nullable String planAmount) {
    this.planAmount = JsonNullable.<String>of(planAmount);
  }


  public IntactChargeInfo productName(@javax.annotation.Nullable String productName) {
    this.productName = JsonNullable.<String>of(productName);
    return this;
  }

  /**
   * Get productName
   * @return productName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getProductName() {
        return productName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PRODUCT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getProductName_JsonNullable() {
    return productName;
  }
  
  @JsonProperty(JSON_PROPERTY_PRODUCT_NAME)
  public void setProductName_JsonNullable(JsonNullable<String> productName) {
    this.productName = productName;
  }

  public void setProductName(@javax.annotation.Nullable String productName) {
    this.productName = JsonNullable.<String>of(productName);
  }


  public IntactChargeInfo serviceTarget(@javax.annotation.Nullable String serviceTarget) {
    this.serviceTarget = JsonNullable.<String>of(serviceTarget);
    return this;
  }

  /**
   * Get serviceTarget
   * @return serviceTarget
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getServiceTarget() {
        return serviceTarget.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SERVICE_TARGET)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getServiceTarget_JsonNullable() {
    return serviceTarget;
  }
  
  @JsonProperty(JSON_PROPERTY_SERVICE_TARGET)
  public void setServiceTarget_JsonNullable(JsonNullable<String> serviceTarget) {
    this.serviceTarget = serviceTarget;
  }

  public void setServiceTarget(@javax.annotation.Nullable String serviceTarget) {
    this.serviceTarget = JsonNullable.<String>of(serviceTarget);
  }


  public IntactChargeInfo serviceType(@javax.annotation.Nullable String serviceType) {
    this.serviceType = JsonNullable.<String>of(serviceType);
    return this;
  }

  /**
   * Get serviceType
   * @return serviceType
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getServiceType() {
        return serviceType.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_SERVICE_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getServiceType_JsonNullable() {
    return serviceType;
  }
  
  @JsonProperty(JSON_PROPERTY_SERVICE_TYPE)
  public void setServiceType_JsonNullable(JsonNullable<String> serviceType) {
    this.serviceType = serviceType;
  }

  public void setServiceType(@javax.annotation.Nullable String serviceType) {
    this.serviceType = JsonNullable.<String>of(serviceType);
  }


  public IntactChargeInfo status(@javax.annotation.Nullable String status) {
    this.status = JsonNullable.<String>of(status);
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getStatus() {
        return status.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getStatus_JsonNullable() {
    return status;
  }
  
  @JsonProperty(JSON_PROPERTY_STATUS)
  public void setStatus_JsonNullable(JsonNullable<String> status) {
    this.status = status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = JsonNullable.<String>of(status);
  }


  public IntactChargeInfo targetAccountNo(@javax.annotation.Nullable String targetAccountNo) {
    this.targetAccountNo = JsonNullable.<String>of(targetAccountNo);
    return this;
  }

  /**
   * Get targetAccountNo
   * @return targetAccountNo
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getTargetAccountNo() {
        return targetAccountNo.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TARGET_ACCOUNT_NO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTargetAccountNo_JsonNullable() {
    return targetAccountNo;
  }
  
  @JsonProperty(JSON_PROPERTY_TARGET_ACCOUNT_NO)
  public void setTargetAccountNo_JsonNullable(JsonNullable<String> targetAccountNo) {
    this.targetAccountNo = targetAccountNo;
  }

  public void setTargetAccountNo(@javax.annotation.Nullable String targetAccountNo) {
    this.targetAccountNo = JsonNullable.<String>of(targetAccountNo);
  }


  public IntactChargeInfo targetUserId(@javax.annotation.Nullable String targetUserId) {
    this.targetUserId = JsonNullable.<String>of(targetUserId);
    return this;
  }

  /**
   * Get targetUserId
   * @return targetUserId
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getTargetUserId() {
        return targetUserId.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TARGET_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTargetUserId_JsonNullable() {
    return targetUserId;
  }
  
  @JsonProperty(JSON_PROPERTY_TARGET_USER_ID)
  public void setTargetUserId_JsonNullable(JsonNullable<String> targetUserId) {
    this.targetUserId = targetUserId;
  }

  public void setTargetUserId(@javax.annotation.Nullable String targetUserId) {
    this.targetUserId = JsonNullable.<String>of(targetUserId);
  }


  /**
   * Return true if this IntactChargeInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IntactChargeInfo intactChargeInfo = (IntactChargeInfo) o;
    return equalsNullable(this.actualAmount, intactChargeInfo.actualAmount) &&
        equalsNullable(this.billType, intactChargeInfo.billType) &&
        equalsNullable(this.gmtPay, intactChargeInfo.gmtPay) &&
        Objects.equals(this.isRefund, intactChargeInfo.isRefund) &&
        equalsNullable(this.outBizNo, intactChargeInfo.outBizNo) &&
        equalsNullable(this.planAmount, intactChargeInfo.planAmount) &&
        equalsNullable(this.productName, intactChargeInfo.productName) &&
        equalsNullable(this.serviceTarget, intactChargeInfo.serviceTarget) &&
        equalsNullable(this.serviceType, intactChargeInfo.serviceType) &&
        equalsNullable(this.status, intactChargeInfo.status) &&
        equalsNullable(this.targetAccountNo, intactChargeInfo.targetAccountNo) &&
        equalsNullable(this.targetUserId, intactChargeInfo.targetUserId);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(actualAmount), hashCodeNullable(billType), hashCodeNullable(gmtPay), isRefund, hashCodeNullable(outBizNo), hashCodeNullable(planAmount), hashCodeNullable(productName), hashCodeNullable(serviceTarget), hashCodeNullable(serviceType), hashCodeNullable(status), hashCodeNullable(targetAccountNo), hashCodeNullable(targetUserId));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IntactChargeInfo {\n");
    sb.append("    actualAmount: ").append(toIndentedString(actualAmount)).append("\n");
    sb.append("    billType: ").append(toIndentedString(billType)).append("\n");
    sb.append("    gmtPay: ").append(toIndentedString(gmtPay)).append("\n");
    sb.append("    isRefund: ").append(toIndentedString(isRefund)).append("\n");
    sb.append("    outBizNo: ").append(toIndentedString(outBizNo)).append("\n");
    sb.append("    planAmount: ").append(toIndentedString(planAmount)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    serviceTarget: ").append(toIndentedString(serviceTarget)).append("\n");
    sb.append("    serviceType: ").append(toIndentedString(serviceType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    targetAccountNo: ").append(toIndentedString(targetAccountNo)).append("\n");
    sb.append("    targetUserId: ").append(toIndentedString(targetUserId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `actualAmount` to the URL query string
    if (getActualAmount() != null) {
      joiner.add(String.format("%sactualAmount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getActualAmount()))));
    }

    // add `billType` to the URL query string
    if (getBillType() != null) {
      joiner.add(String.format("%sbillType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBillType()))));
    }

    // add `gmtPay` to the URL query string
    if (getGmtPay() != null) {
      joiner.add(String.format("%sgmtPay%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGmtPay()))));
    }

    // add `isRefund` to the URL query string
    if (getIsRefund() != null) {
      joiner.add(String.format("%sisRefund%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getIsRefund()))));
    }

    // add `outBizNo` to the URL query string
    if (getOutBizNo() != null) {
      joiner.add(String.format("%soutBizNo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOutBizNo()))));
    }

    // add `planAmount` to the URL query string
    if (getPlanAmount() != null) {
      joiner.add(String.format("%splanAmount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlanAmount()))));
    }

    // add `productName` to the URL query string
    if (getProductName() != null) {
      joiner.add(String.format("%sproductName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProductName()))));
    }

    // add `serviceTarget` to the URL query string
    if (getServiceTarget() != null) {
      joiner.add(String.format("%sserviceTarget%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServiceTarget()))));
    }

    // add `serviceType` to the URL query string
    if (getServiceType() != null) {
      joiner.add(String.format("%sserviceType%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getServiceType()))));
    }

    // add `status` to the URL query string
    if (getStatus() != null) {
      joiner.add(String.format("%sstatus%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getStatus()))));
    }

    // add `targetAccountNo` to the URL query string
    if (getTargetAccountNo() != null) {
      joiner.add(String.format("%stargetAccountNo%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTargetAccountNo()))));
    }

    // add `targetUserId` to the URL query string
    if (getTargetUserId() != null) {
      joiner.add(String.format("%stargetUserId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTargetUserId()))));
    }

    return joiner.toString();
  }
}

