/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zashigaofa.client.ApiClient;
/**
 * 公共配置存储实体，用于集中管理系统的配置项。
 */
@JsonPropertyOrder({
  Settings.JSON_PROPERTY_ID,
  Settings.JSON_PROPERTY_BIZ_CODE,
  Settings.JSON_PROPERTY_BIZ_IDENTITY,
  Settings.JSON_PROPERTY_PROVIDER_CODE,
  Settings.JSON_PROPERTY_GROUP_CODE,
  Settings.JSON_PROPERTY_CODE,
  Settings.JSON_PROPERTY_VALUE,
  Settings.JSON_PROPERTY_TAGS,
  Settings.JSON_PROPERTY_DESCRIPTION,
  Settings.JSON_PROPERTY_FRONTEND_USABLE,
  Settings.JSON_PROPERTY_CREATE_DATE,
  Settings.JSON_PROPERTY_LAST_UPDATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-15T06:11:08.446207689Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class Settings {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_BIZ_CODE = "bizCode";
  private JsonNullable<String> bizCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BIZ_IDENTITY = "bizIdentity";
  private JsonNullable<String> bizIdentity = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PROVIDER_CODE = "providerCode";
  private JsonNullable<String> providerCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_GROUP_CODE = "groupCode";
  private JsonNullable<String> groupCode = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CODE = "code";
  private JsonNullable<String> code = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_VALUE = "value";
  private JsonNullable<String> value = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_TAGS = "tags";
  private JsonNullable<String> tags = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_FRONTEND_USABLE = "frontendUsable";
  @javax.annotation.Nullable
  private Boolean frontendUsable;

  public static final String JSON_PROPERTY_CREATE_DATE = "createDate";
  @javax.annotation.Nullable
  private OffsetDateTime createDate;

  public static final String JSON_PROPERTY_LAST_UPDATE = "lastUpdate";
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdate;

  public Settings() { 
  }

  public Settings id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * 配置项的唯一标识符。
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public Settings bizCode(@javax.annotation.Nullable String bizCode) {
    this.bizCode = JsonNullable.<String>of(bizCode);
    return this;
  }

  /**
   * 配置项所属的业务代码，用于分类管理。
   * @return bizCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getBizCode() {
        return bizCode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BIZ_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBizCode_JsonNullable() {
    return bizCode;
  }
  
  @JsonProperty(JSON_PROPERTY_BIZ_CODE)
  public void setBizCode_JsonNullable(JsonNullable<String> bizCode) {
    this.bizCode = bizCode;
  }

  public void setBizCode(@javax.annotation.Nullable String bizCode) {
    this.bizCode = JsonNullable.<String>of(bizCode);
  }


  public Settings bizIdentity(@javax.annotation.Nullable String bizIdentity) {
    this.bizIdentity = JsonNullable.<String>of(bizIdentity);
    return this;
  }

  /**
   * 配置项所属的业务标识，用于唯一标识业务。
   * @return bizIdentity
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getBizIdentity() {
        return bizIdentity.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_BIZ_IDENTITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBizIdentity_JsonNullable() {
    return bizIdentity;
  }
  
  @JsonProperty(JSON_PROPERTY_BIZ_IDENTITY)
  public void setBizIdentity_JsonNullable(JsonNullable<String> bizIdentity) {
    this.bizIdentity = bizIdentity;
  }

  public void setBizIdentity(@javax.annotation.Nullable String bizIdentity) {
    this.bizIdentity = JsonNullable.<String>of(bizIdentity);
  }


  public Settings providerCode(@javax.annotation.Nullable String providerCode) {
    this.providerCode = JsonNullable.<String>of(providerCode);
    return this;
  }

  /**
   * 配置项的提供者代码，用于标识配置来源。
   * @return providerCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getProviderCode() {
        return providerCode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PROVIDER_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getProviderCode_JsonNullable() {
    return providerCode;
  }
  
  @JsonProperty(JSON_PROPERTY_PROVIDER_CODE)
  public void setProviderCode_JsonNullable(JsonNullable<String> providerCode) {
    this.providerCode = providerCode;
  }

  public void setProviderCode(@javax.annotation.Nullable String providerCode) {
    this.providerCode = JsonNullable.<String>of(providerCode);
  }


  public Settings groupCode(@javax.annotation.Nullable String groupCode) {
    this.groupCode = JsonNullable.<String>of(groupCode);
    return this;
  }

  /**
   * 配置项的分组代码，用于组织和管理相关配置。
   * @return groupCode
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getGroupCode() {
        return groupCode.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_GROUP_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getGroupCode_JsonNullable() {
    return groupCode;
  }
  
  @JsonProperty(JSON_PROPERTY_GROUP_CODE)
  public void setGroupCode_JsonNullable(JsonNullable<String> groupCode) {
    this.groupCode = groupCode;
  }

  public void setGroupCode(@javax.annotation.Nullable String groupCode) {
    this.groupCode = JsonNullable.<String>of(groupCode);
  }


  public Settings code(@javax.annotation.Nullable String code) {
    this.code = JsonNullable.<String>of(code);
    return this;
  }

  /**
   * 配置项的唯一代码，用于标识具体的配置项。
   * @return code
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getCode() {
        return code.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getCode_JsonNullable() {
    return code;
  }
  
  @JsonProperty(JSON_PROPERTY_CODE)
  public void setCode_JsonNullable(JsonNullable<String> code) {
    this.code = code;
  }

  public void setCode(@javax.annotation.Nullable String code) {
    this.code = JsonNullable.<String>of(code);
  }


  public Settings value(@javax.annotation.Nullable String value) {
    this.value = JsonNullable.<String>of(value);
    return this;
  }

  /**
   * 配置项的具体值，存储配置内容。
   * @return value
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getValue() {
        return value.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getValue_JsonNullable() {
    return value;
  }
  
  @JsonProperty(JSON_PROPERTY_VALUE)
  public void setValue_JsonNullable(JsonNullable<String> value) {
    this.value = value;
  }

  public void setValue(@javax.annotation.Nullable String value) {
    this.value = JsonNullable.<String>of(value);
  }


  public Settings tags(@javax.annotation.Nullable String tags) {
    this.tags = JsonNullable.<String>of(tags);
    return this;
  }

  /**
   * 用于分类或标记配置项的标签。
   * @return tags
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getTags() {
        return tags.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TAGS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTags_JsonNullable() {
    return tags;
  }
  
  @JsonProperty(JSON_PROPERTY_TAGS)
  public void setTags_JsonNullable(JsonNullable<String> tags) {
    this.tags = tags;
  }

  public void setTags(@javax.annotation.Nullable String tags) {
    this.tags = JsonNullable.<String>of(tags);
  }


  public Settings description(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * 配置项的详细描述，说明其用途和作用。
   * @return description
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  public Settings frontendUsable(@javax.annotation.Nullable Boolean frontendUsable) {
    this.frontendUsable = frontendUsable;
    return this;
  }

  /**
   * 指示该配置项是否可供前端使用。
   * @return frontendUsable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FRONTEND_USABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getFrontendUsable() {
    return frontendUsable;
  }


  @JsonProperty(JSON_PROPERTY_FRONTEND_USABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFrontendUsable(@javax.annotation.Nullable Boolean frontendUsable) {
    this.frontendUsable = frontendUsable;
  }


  public Settings createDate(@javax.annotation.Nullable OffsetDateTime createDate) {
    this.createDate = createDate;
    return this;
  }

  /**
   * 配置项的创建日期，默认为当前时间。
   * @return createDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreateDate() {
    return createDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateDate(@javax.annotation.Nullable OffsetDateTime createDate) {
    this.createDate = createDate;
  }


  public Settings lastUpdate(@javax.annotation.Nullable OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

  /**
   * 配置项的最后更新日期，默认为当前时间。
   * @return lastUpdate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getLastUpdate() {
    return lastUpdate;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdate(@javax.annotation.Nullable OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
  }


  /**
   * Return true if this Settings object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Settings settings = (Settings) o;
    return Objects.equals(this.id, settings.id) &&
        equalsNullable(this.bizCode, settings.bizCode) &&
        equalsNullable(this.bizIdentity, settings.bizIdentity) &&
        equalsNullable(this.providerCode, settings.providerCode) &&
        equalsNullable(this.groupCode, settings.groupCode) &&
        equalsNullable(this.code, settings.code) &&
        equalsNullable(this.value, settings.value) &&
        equalsNullable(this.tags, settings.tags) &&
        equalsNullable(this.description, settings.description) &&
        Objects.equals(this.frontendUsable, settings.frontendUsable) &&
        Objects.equals(this.createDate, settings.createDate) &&
        Objects.equals(this.lastUpdate, settings.lastUpdate);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hashCodeNullable(bizCode), hashCodeNullable(bizIdentity), hashCodeNullable(providerCode), hashCodeNullable(groupCode), hashCodeNullable(code), hashCodeNullable(value), hashCodeNullable(tags), hashCodeNullable(description), frontendUsable, createDate, lastUpdate);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Settings {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    bizCode: ").append(toIndentedString(bizCode)).append("\n");
    sb.append("    bizIdentity: ").append(toIndentedString(bizIdentity)).append("\n");
    sb.append("    providerCode: ").append(toIndentedString(providerCode)).append("\n");
    sb.append("    groupCode: ").append(toIndentedString(groupCode)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    frontendUsable: ").append(toIndentedString(frontendUsable)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `bizCode` to the URL query string
    if (getBizCode() != null) {
      joiner.add(String.format("%sbizCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBizCode()))));
    }

    // add `bizIdentity` to the URL query string
    if (getBizIdentity() != null) {
      joiner.add(String.format("%sbizIdentity%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getBizIdentity()))));
    }

    // add `providerCode` to the URL query string
    if (getProviderCode() != null) {
      joiner.add(String.format("%sproviderCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getProviderCode()))));
    }

    // add `groupCode` to the URL query string
    if (getGroupCode() != null) {
      joiner.add(String.format("%sgroupCode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getGroupCode()))));
    }

    // add `code` to the URL query string
    if (getCode() != null) {
      joiner.add(String.format("%scode%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCode()))));
    }

    // add `value` to the URL query string
    if (getValue() != null) {
      joiner.add(String.format("%svalue%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getValue()))));
    }

    // add `tags` to the URL query string
    if (getTags() != null) {
      joiner.add(String.format("%stags%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTags()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `frontendUsable` to the URL query string
    if (getFrontendUsable() != null) {
      joiner.add(String.format("%sfrontendUsable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getFrontendUsable()))));
    }

    // add `createDate` to the URL query string
    if (getCreateDate() != null) {
      joiner.add(String.format("%screateDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreateDate()))));
    }

    // add `lastUpdate` to the URL query string
    if (getLastUpdate() != null) {
      joiner.add(String.format("%slastUpdate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastUpdate()))));
    }

    return joiner.toString();
  }
}

