/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zashigaofa.client.ApiClient;
/**
 * Tenant
 */
@JsonPropertyOrder({
  Tenant.JSON_PROPERTY_ID,
  Tenant.JSON_PROPERTY_NAME,
  Tenant.JSON_PROPERTY_OWNER_ID,
  Tenant.JSON_PROPERTY_THEME,
  Tenant.JSON_PROPERTY_CLAIMS_ISSUER,
  Tenant.JSON_PROPERTY_OWNER_HOST,
  Tenant.JSON_PROPERTY_LOGO_URI,
  Tenant.JSON_PROPERTY_DESCRIPTION,
  Tenant.JSON_PROPERTY_WEB_HOOK_URI,
  Tenant.JSON_PROPERTY_SHOW,
  Tenant.JSON_PROPERTY_CREATE_DATE,
  Tenant.JSON_PROPERTY_LAST_UPDATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-22T08:55:19.994923193Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class Tenant {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_NAME = "name";
  private JsonNullable<String> name = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_OWNER_ID = "ownerId";
  @javax.annotation.Nullable
  private Long ownerId;

  public static final String JSON_PROPERTY_THEME = "theme";
  private JsonNullable<String> theme = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CLAIMS_ISSUER = "claimsIssuer";
  private JsonNullable<String> claimsIssuer = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_OWNER_HOST = "ownerHost";
  private JsonNullable<String> ownerHost = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_LOGO_URI = "logoUri";
  private JsonNullable<String> logoUri = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_WEB_HOOK_URI = "webHookUri";
  private JsonNullable<String> webHookUri = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SHOW = "show";
  @javax.annotation.Nullable
  private Boolean show;

  public static final String JSON_PROPERTY_CREATE_DATE = "createDate";
  @javax.annotation.Nullable
  private OffsetDateTime createDate;

  public static final String JSON_PROPERTY_LAST_UPDATE = "lastUpdate";
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdate;

  public Tenant() { 
  }

  public Tenant id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public Tenant name(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getName() {
        return name.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getName_JsonNullable() {
    return name;
  }
  
  @JsonProperty(JSON_PROPERTY_NAME)
  public void setName_JsonNullable(JsonNullable<String> name) {
    this.name = name;
  }

  public void setName(@javax.annotation.Nullable String name) {
    this.name = JsonNullable.<String>of(name);
  }


  public Tenant ownerId(@javax.annotation.Nullable Long ownerId) {
    this.ownerId = ownerId;
    return this;
  }

  /**
   * Get ownerId
   * @return ownerId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getOwnerId() {
    return ownerId;
  }


  @JsonProperty(JSON_PROPERTY_OWNER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwnerId(@javax.annotation.Nullable Long ownerId) {
    this.ownerId = ownerId;
  }


  public Tenant theme(@javax.annotation.Nullable String theme) {
    this.theme = JsonNullable.<String>of(theme);
    return this;
  }

  /**
   * Get theme
   * @return theme
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getTheme() {
        return theme.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_THEME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTheme_JsonNullable() {
    return theme;
  }
  
  @JsonProperty(JSON_PROPERTY_THEME)
  public void setTheme_JsonNullable(JsonNullable<String> theme) {
    this.theme = theme;
  }

  public void setTheme(@javax.annotation.Nullable String theme) {
    this.theme = JsonNullable.<String>of(theme);
  }


  public Tenant claimsIssuer(@javax.annotation.Nullable String claimsIssuer) {
    this.claimsIssuer = JsonNullable.<String>of(claimsIssuer);
    return this;
  }

  /**
   * Get claimsIssuer
   * @return claimsIssuer
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getClaimsIssuer() {
        return claimsIssuer.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_CLAIMS_ISSUER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getClaimsIssuer_JsonNullable() {
    return claimsIssuer;
  }
  
  @JsonProperty(JSON_PROPERTY_CLAIMS_ISSUER)
  public void setClaimsIssuer_JsonNullable(JsonNullable<String> claimsIssuer) {
    this.claimsIssuer = claimsIssuer;
  }

  public void setClaimsIssuer(@javax.annotation.Nullable String claimsIssuer) {
    this.claimsIssuer = JsonNullable.<String>of(claimsIssuer);
  }


  public Tenant ownerHost(@javax.annotation.Nullable String ownerHost) {
    this.ownerHost = JsonNullable.<String>of(ownerHost);
    return this;
  }

  /**
   * Get ownerHost
   * @return ownerHost
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getOwnerHost() {
        return ownerHost.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_OWNER_HOST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getOwnerHost_JsonNullable() {
    return ownerHost;
  }
  
  @JsonProperty(JSON_PROPERTY_OWNER_HOST)
  public void setOwnerHost_JsonNullable(JsonNullable<String> ownerHost) {
    this.ownerHost = ownerHost;
  }

  public void setOwnerHost(@javax.annotation.Nullable String ownerHost) {
    this.ownerHost = JsonNullable.<String>of(ownerHost);
  }


  public Tenant logoUri(@javax.annotation.Nullable String logoUri) {
    this.logoUri = JsonNullable.<String>of(logoUri);
    return this;
  }

  /**
   * Get logoUri
   * @return logoUri
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getLogoUri() {
        return logoUri.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_LOGO_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLogoUri_JsonNullable() {
    return logoUri;
  }
  
  @JsonProperty(JSON_PROPERTY_LOGO_URI)
  public void setLogoUri_JsonNullable(JsonNullable<String> logoUri) {
    this.logoUri = logoUri;
  }

  public void setLogoUri(@javax.annotation.Nullable String logoUri) {
    this.logoUri = JsonNullable.<String>of(logoUri);
  }


  public Tenant description(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getDescription() {
        return description.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  public Tenant webHookUri(@javax.annotation.Nullable String webHookUri) {
    this.webHookUri = JsonNullable.<String>of(webHookUri);
    return this;
  }

  /**
   * Get webHookUri
   * @return webHookUri
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getWebHookUri() {
        return webHookUri.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_WEB_HOOK_URI)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getWebHookUri_JsonNullable() {
    return webHookUri;
  }
  
  @JsonProperty(JSON_PROPERTY_WEB_HOOK_URI)
  public void setWebHookUri_JsonNullable(JsonNullable<String> webHookUri) {
    this.webHookUri = webHookUri;
  }

  public void setWebHookUri(@javax.annotation.Nullable String webHookUri) {
    this.webHookUri = JsonNullable.<String>of(webHookUri);
  }


  public Tenant show(@javax.annotation.Nullable Boolean show) {
    this.show = show;
    return this;
  }

  /**
   * Get show
   * @return show
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getShow() {
    return show;
  }


  @JsonProperty(JSON_PROPERTY_SHOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShow(@javax.annotation.Nullable Boolean show) {
    this.show = show;
  }


  public Tenant createDate(@javax.annotation.Nullable OffsetDateTime createDate) {
    this.createDate = createDate;
    return this;
  }

  /**
   * Get createDate
   * @return createDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreateDate() {
    return createDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateDate(@javax.annotation.Nullable OffsetDateTime createDate) {
    this.createDate = createDate;
  }


  public Tenant lastUpdate(@javax.annotation.Nullable OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

  /**
   * Get lastUpdate
   * @return lastUpdate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getLastUpdate() {
    return lastUpdate;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdate(@javax.annotation.Nullable OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
  }


  /**
   * Return true if this Tenant object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tenant tenant = (Tenant) o;
    return Objects.equals(this.id, tenant.id) &&
        equalsNullable(this.name, tenant.name) &&
        Objects.equals(this.ownerId, tenant.ownerId) &&
        equalsNullable(this.theme, tenant.theme) &&
        equalsNullable(this.claimsIssuer, tenant.claimsIssuer) &&
        equalsNullable(this.ownerHost, tenant.ownerHost) &&
        equalsNullable(this.logoUri, tenant.logoUri) &&
        equalsNullable(this.description, tenant.description) &&
        equalsNullable(this.webHookUri, tenant.webHookUri) &&
        Objects.equals(this.show, tenant.show) &&
        Objects.equals(this.createDate, tenant.createDate) &&
        Objects.equals(this.lastUpdate, tenant.lastUpdate);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, hashCodeNullable(name), ownerId, hashCodeNullable(theme), hashCodeNullable(claimsIssuer), hashCodeNullable(ownerHost), hashCodeNullable(logoUri), hashCodeNullable(description), hashCodeNullable(webHookUri), show, createDate, lastUpdate);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tenant {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    theme: ").append(toIndentedString(theme)).append("\n");
    sb.append("    claimsIssuer: ").append(toIndentedString(claimsIssuer)).append("\n");
    sb.append("    ownerHost: ").append(toIndentedString(ownerHost)).append("\n");
    sb.append("    logoUri: ").append(toIndentedString(logoUri)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    webHookUri: ").append(toIndentedString(webHookUri)).append("\n");
    sb.append("    show: ").append(toIndentedString(show)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `name` to the URL query string
    if (getName() != null) {
      joiner.add(String.format("%sname%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getName()))));
    }

    // add `ownerId` to the URL query string
    if (getOwnerId() != null) {
      joiner.add(String.format("%sownerId%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOwnerId()))));
    }

    // add `theme` to the URL query string
    if (getTheme() != null) {
      joiner.add(String.format("%stheme%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTheme()))));
    }

    // add `claimsIssuer` to the URL query string
    if (getClaimsIssuer() != null) {
      joiner.add(String.format("%sclaimsIssuer%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getClaimsIssuer()))));
    }

    // add `ownerHost` to the URL query string
    if (getOwnerHost() != null) {
      joiner.add(String.format("%sownerHost%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getOwnerHost()))));
    }

    // add `logoUri` to the URL query string
    if (getLogoUri() != null) {
      joiner.add(String.format("%slogoUri%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLogoUri()))));
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      joiner.add(String.format("%sdescription%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getDescription()))));
    }

    // add `webHookUri` to the URL query string
    if (getWebHookUri() != null) {
      joiner.add(String.format("%swebHookUri%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getWebHookUri()))));
    }

    // add `show` to the URL query string
    if (getShow() != null) {
      joiner.add(String.format("%sshow%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getShow()))));
    }

    // add `createDate` to the URL query string
    if (getCreateDate() != null) {
      joiner.add(String.format("%screateDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreateDate()))));
    }

    // add `lastUpdate` to the URL query string
    if (getLastUpdate() != null) {
      joiner.add(String.format("%slastUpdate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastUpdate()))));
    }

    return joiner.toString();
  }
}

