/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.zashigaofa.client.model.TradeSettleDetail;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zashigaofa.client.ApiClient;
/**
 * TradeSettleInfo
 */
@JsonPropertyOrder({
  TradeSettleInfo.JSON_PROPERTY_TRADE_SETTLE_DETAIL_LIST,
  TradeSettleInfo.JSON_PROPERTY_TRADE_UNSETTLED_AMOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-10T08:59:39.754837544Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class TradeSettleInfo {
  public static final String JSON_PROPERTY_TRADE_SETTLE_DETAIL_LIST = "tradeSettleDetailList";
  private JsonNullable<List<TradeSettleDetail>> tradeSettleDetailList = JsonNullable.<List<TradeSettleDetail>>undefined();

  public static final String JSON_PROPERTY_TRADE_UNSETTLED_AMOUNT = "tradeUnsettledAmount";
  private JsonNullable<String> tradeUnsettledAmount = JsonNullable.<String>undefined();

  public TradeSettleInfo() { 
  }

  public TradeSettleInfo tradeSettleDetailList(@javax.annotation.Nullable List<TradeSettleDetail> tradeSettleDetailList) {
    this.tradeSettleDetailList = JsonNullable.<List<TradeSettleDetail>>of(tradeSettleDetailList);
    return this;
  }

  public TradeSettleInfo addTradeSettleDetailListItem(TradeSettleDetail tradeSettleDetailListItem) {
    if (this.tradeSettleDetailList == null || !this.tradeSettleDetailList.isPresent()) {
      this.tradeSettleDetailList = JsonNullable.<List<TradeSettleDetail>>of(new ArrayList<>());
    }
    try {
      this.tradeSettleDetailList.get().add(tradeSettleDetailListItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Get tradeSettleDetailList
   * @return tradeSettleDetailList
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public List<TradeSettleDetail> getTradeSettleDetailList() {
        return tradeSettleDetailList.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TRADE_SETTLE_DETAIL_LIST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<List<TradeSettleDetail>> getTradeSettleDetailList_JsonNullable() {
    return tradeSettleDetailList;
  }
  
  @JsonProperty(JSON_PROPERTY_TRADE_SETTLE_DETAIL_LIST)
  public void setTradeSettleDetailList_JsonNullable(JsonNullable<List<TradeSettleDetail>> tradeSettleDetailList) {
    this.tradeSettleDetailList = tradeSettleDetailList;
  }

  public void setTradeSettleDetailList(@javax.annotation.Nullable List<TradeSettleDetail> tradeSettleDetailList) {
    this.tradeSettleDetailList = JsonNullable.<List<TradeSettleDetail>>of(tradeSettleDetailList);
  }


  public TradeSettleInfo tradeUnsettledAmount(@javax.annotation.Nullable String tradeUnsettledAmount) {
    this.tradeUnsettledAmount = JsonNullable.<String>of(tradeUnsettledAmount);
    return this;
  }

  /**
   * Get tradeUnsettledAmount
   * @return tradeUnsettledAmount
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getTradeUnsettledAmount() {
        return tradeUnsettledAmount.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_TRADE_UNSETTLED_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getTradeUnsettledAmount_JsonNullable() {
    return tradeUnsettledAmount;
  }
  
  @JsonProperty(JSON_PROPERTY_TRADE_UNSETTLED_AMOUNT)
  public void setTradeUnsettledAmount_JsonNullable(JsonNullable<String> tradeUnsettledAmount) {
    this.tradeUnsettledAmount = tradeUnsettledAmount;
  }

  public void setTradeUnsettledAmount(@javax.annotation.Nullable String tradeUnsettledAmount) {
    this.tradeUnsettledAmount = JsonNullable.<String>of(tradeUnsettledAmount);
  }


  /**
   * Return true if this TradeSettleInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TradeSettleInfo tradeSettleInfo = (TradeSettleInfo) o;
    return equalsNullable(this.tradeSettleDetailList, tradeSettleInfo.tradeSettleDetailList) &&
        equalsNullable(this.tradeUnsettledAmount, tradeSettleInfo.tradeUnsettledAmount);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(tradeSettleDetailList), hashCodeNullable(tradeUnsettledAmount));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TradeSettleInfo {\n");
    sb.append("    tradeSettleDetailList: ").append(toIndentedString(tradeSettleDetailList)).append("\n");
    sb.append("    tradeUnsettledAmount: ").append(toIndentedString(tradeUnsettledAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `tradeSettleDetailList` to the URL query string
    if (getTradeSettleDetailList() != null) {
      for (int i = 0; i < getTradeSettleDetailList().size(); i++) {
        if (getTradeSettleDetailList().get(i) != null) {
          joiner.add(getTradeSettleDetailList().get(i).toUrlQueryString(String.format("%stradeSettleDetailList%s%s", prefix, suffix,
          "".equals(suffix) ? "" : String.format("%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `tradeUnsettledAmount` to the URL query string
    if (getTradeUnsettledAmount() != null) {
      joiner.add(String.format("%stradeUnsettledAmount%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getTradeUnsettledAmount()))));
    }

    return joiner.toString();
  }
}

