/*
 * 用户全部 API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.zashigaofa.client.ApiClient;
/**
 * 用户外部账号
 */
@JsonPropertyOrder({
  UserLogins.JSON_PROPERTY_ID,
  UserLogins.JSON_PROPERTY_USER_I_D,
  UserLogins.JSON_PROPERTY_PLATFORM_NAME,
  UserLogins.JSON_PROPERTY_PLATFORM,
  UserLogins.JSON_PROPERTY_UNION_I_D,
  UserLogins.JSON_PROPERTY_AVATAR,
  UserLogins.JSON_PROPERTY_DATA,
  UserLogins.JSON_PROPERTY_ENABLE,
  UserLogins.JSON_PROPERTY_CREATE_DATE,
  UserLogins.JSON_PROPERTY_LAST_UPDATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-11-10T08:59:39.754837544Z[Etc/UTC]", comments = "Generator version: 7.13.0-SNAPSHOT")
public class UserLogins {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_USER_I_D = "userID";
  @javax.annotation.Nullable
  private Long userID;

  public static final String JSON_PROPERTY_PLATFORM_NAME = "platformName";
  private JsonNullable<String> platformName = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_PLATFORM = "platform";
  private JsonNullable<String> platform = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_UNION_I_D = "unionID";
  private JsonNullable<String> unionID = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVATAR = "avatar";
  private JsonNullable<String> avatar = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_DATA = "data";
  private JsonNullable<String> data = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_ENABLE = "enable";
  @javax.annotation.Nullable
  private Boolean enable;

  public static final String JSON_PROPERTY_CREATE_DATE = "createDate";
  @javax.annotation.Nullable
  private OffsetDateTime createDate;

  public static final String JSON_PROPERTY_LAST_UPDATE = "lastUpdate";
  @javax.annotation.Nullable
  private OffsetDateTime lastUpdate;

  public UserLogins() { 
  }

  public UserLogins id(@javax.annotation.Nullable Long id) {
    this.id = id;
    return this;
  }

  /**
   * 唯一标识符
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable Long id) {
    this.id = id;
  }


  public UserLogins userID(@javax.annotation.Nullable Long userID) {
    this.userID = userID;
    return this;
  }

  /**
   * 关联的用户ID
   * @return userID
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getUserID() {
    return userID;
  }


  @JsonProperty(JSON_PROPERTY_USER_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserID(@javax.annotation.Nullable Long userID) {
    this.userID = userID;
  }


  public UserLogins platformName(@javax.annotation.Nullable String platformName) {
    this.platformName = JsonNullable.<String>of(platformName);
    return this;
  }

  /**
   * 第三方平台名称
   * @return platformName
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPlatformName() {
        return platformName.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PLATFORM_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPlatformName_JsonNullable() {
    return platformName;
  }
  
  @JsonProperty(JSON_PROPERTY_PLATFORM_NAME)
  public void setPlatformName_JsonNullable(JsonNullable<String> platformName) {
    this.platformName = platformName;
  }

  public void setPlatformName(@javax.annotation.Nullable String platformName) {
    this.platformName = JsonNullable.<String>of(platformName);
  }


  public UserLogins platform(@javax.annotation.Nullable String platform) {
    this.platform = JsonNullable.<String>of(platform);
    return this;
  }

  /**
   * 第三方平台
   * @return platform
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getPlatform() {
        return platform.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_PLATFORM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getPlatform_JsonNullable() {
    return platform;
  }
  
  @JsonProperty(JSON_PROPERTY_PLATFORM)
  public void setPlatform_JsonNullable(JsonNullable<String> platform) {
    this.platform = platform;
  }

  public void setPlatform(@javax.annotation.Nullable String platform) {
    this.platform = JsonNullable.<String>of(platform);
  }


  public UserLogins unionID(@javax.annotation.Nullable String unionID) {
    this.unionID = JsonNullable.<String>of(unionID);
    return this;
  }

  /**
   * 第三方平台唯一标识
   * @return unionID
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getUnionID() {
        return unionID.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_UNION_I_D)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUnionID_JsonNullable() {
    return unionID;
  }
  
  @JsonProperty(JSON_PROPERTY_UNION_I_D)
  public void setUnionID_JsonNullable(JsonNullable<String> unionID) {
    this.unionID = unionID;
  }

  public void setUnionID(@javax.annotation.Nullable String unionID) {
    this.unionID = JsonNullable.<String>of(unionID);
  }


  public UserLogins avatar(@javax.annotation.Nullable String avatar) {
    this.avatar = JsonNullable.<String>of(avatar);
    return this;
  }

  /**
   * 用户头像
   * @return avatar
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getAvatar() {
        return avatar.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_AVATAR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAvatar_JsonNullable() {
    return avatar;
  }
  
  @JsonProperty(JSON_PROPERTY_AVATAR)
  public void setAvatar_JsonNullable(JsonNullable<String> avatar) {
    this.avatar = avatar;
  }

  public void setAvatar(@javax.annotation.Nullable String avatar) {
    this.avatar = JsonNullable.<String>of(avatar);
  }


  public UserLogins data(@javax.annotation.Nullable String data) {
    this.data = JsonNullable.<String>of(data);
    return this;
  }

  /**
   * 扩展数据
   * @return data
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getData() {
        return data.orElse(null);
  }

  @JsonProperty(JSON_PROPERTY_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getData_JsonNullable() {
    return data;
  }
  
  @JsonProperty(JSON_PROPERTY_DATA)
  public void setData_JsonNullable(JsonNullable<String> data) {
    this.data = data;
  }

  public void setData(@javax.annotation.Nullable String data) {
    this.data = JsonNullable.<String>of(data);
  }


  public UserLogins enable(@javax.annotation.Nullable Boolean enable) {
    this.enable = enable;
    return this;
  }

  /**
   * 启用
   * @return enable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getEnable() {
    return enable;
  }


  @JsonProperty(JSON_PROPERTY_ENABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnable(@javax.annotation.Nullable Boolean enable) {
    this.enable = enable;
  }


  public UserLogins createDate(@javax.annotation.Nullable OffsetDateTime createDate) {
    this.createDate = createDate;
    return this;
  }

  /**
   * 创建时间
   * @return createDate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreateDate() {
    return createDate;
  }


  @JsonProperty(JSON_PROPERTY_CREATE_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreateDate(@javax.annotation.Nullable OffsetDateTime createDate) {
    this.createDate = createDate;
  }


  public UserLogins lastUpdate(@javax.annotation.Nullable OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

  /**
   * 最后更新时间
   * @return lastUpdate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getLastUpdate() {
    return lastUpdate;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastUpdate(@javax.annotation.Nullable OffsetDateTime lastUpdate) {
    this.lastUpdate = lastUpdate;
  }


  /**
   * Return true if this UserLogins object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserLogins userLogins = (UserLogins) o;
    return Objects.equals(this.id, userLogins.id) &&
        Objects.equals(this.userID, userLogins.userID) &&
        equalsNullable(this.platformName, userLogins.platformName) &&
        equalsNullable(this.platform, userLogins.platform) &&
        equalsNullable(this.unionID, userLogins.unionID) &&
        equalsNullable(this.avatar, userLogins.avatar) &&
        equalsNullable(this.data, userLogins.data) &&
        Objects.equals(this.enable, userLogins.enable) &&
        Objects.equals(this.createDate, userLogins.createDate) &&
        Objects.equals(this.lastUpdate, userLogins.lastUpdate);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, userID, hashCodeNullable(platformName), hashCodeNullable(platform), hashCodeNullable(unionID), hashCodeNullable(avatar), hashCodeNullable(data), enable, createDate, lastUpdate);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserLogins {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    userID: ").append(toIndentedString(userID)).append("\n");
    sb.append("    platformName: ").append(toIndentedString(platformName)).append("\n");
    sb.append("    platform: ").append(toIndentedString(platform)).append("\n");
    sb.append("    unionID: ").append(toIndentedString(unionID)).append("\n");
    sb.append("    avatar: ").append(toIndentedString(avatar)).append("\n");
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("    enable: ").append(toIndentedString(enable)).append("\n");
    sb.append("    createDate: ").append(toIndentedString(createDate)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `id` to the URL query string
    if (getId() != null) {
      joiner.add(String.format("%sid%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getId()))));
    }

    // add `userID` to the URL query string
    if (getUserID() != null) {
      joiner.add(String.format("%suserID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUserID()))));
    }

    // add `platformName` to the URL query string
    if (getPlatformName() != null) {
      joiner.add(String.format("%splatformName%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatformName()))));
    }

    // add `platform` to the URL query string
    if (getPlatform() != null) {
      joiner.add(String.format("%splatform%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getPlatform()))));
    }

    // add `unionID` to the URL query string
    if (getUnionID() != null) {
      joiner.add(String.format("%sunionID%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getUnionID()))));
    }

    // add `avatar` to the URL query string
    if (getAvatar() != null) {
      joiner.add(String.format("%savatar%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getAvatar()))));
    }

    // add `data` to the URL query string
    if (getData() != null) {
      joiner.add(String.format("%sdata%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getData()))));
    }

    // add `enable` to the URL query string
    if (getEnable() != null) {
      joiner.add(String.format("%senable%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getEnable()))));
    }

    // add `createDate` to the URL query string
    if (getCreateDate() != null) {
      joiner.add(String.format("%screateDate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getCreateDate()))));
    }

    // add `lastUpdate` to the URL query string
    if (getLastUpdate() != null) {
      joiner.add(String.format("%slastUpdate%s=%s", prefix, suffix, ApiClient.urlEncode(ApiClient.valueToString(getLastUpdate()))));
    }

    return joiner.toString();
  }
}

