/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.api;

import com.zashigaofa.client.ApiException;
import com.zashigaofa.client.model.AccessTokenPostRequest;
import com.zashigaofa.client.model.AccessTokenPutRequest;
import com.zashigaofa.client.model.JObjectApiResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for AccessTokenApi
 */
@Disabled
public class AccessTokenApiTest {

    private final AccessTokenApi api = new AccessTokenApi();

    
    /**
     * 删除令牌
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accessTokenDeleteTest() throws ApiException {
        Long id = null;
        String appKey = null;
        JObjectApiResult response = 
        api.accessTokenDelete(id, appKey);
        
        // TODO: test validations
    }
    
    /**
     * 创建令牌
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accessTokenPostTest() throws ApiException {
        String appKey = null;
        AccessTokenPostRequest accessTokenPostRequest = null;
        JObjectApiResult response = 
        api.accessTokenPost(appKey, accessTokenPostRequest);
        
        // TODO: test validations
    }
    
    /**
     * 更新令牌
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accessTokenPutTest() throws ApiException {
        Long id = null;
        String appKey = null;
        AccessTokenPutRequest accessTokenPutRequest = null;
        JObjectApiResult response = 
        api.accessTokenPut(id, appKey, accessTokenPutRequest);
        
        // TODO: test validations
    }
    
    /**
     * 令牌列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void accessTokensTest() throws ApiException {
        String appKey = null;
        Long userId = null;
        Integer skip = null;
        Integer take = null;
        JObjectApiResult response = 
        api.accessTokens(appKey, userId, skip, take);
        
        // TODO: test validations
    }
    
}
