/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.api;

import com.zashigaofa.client.ApiException;
import com.zashigaofa.client.model.Currency;
import com.zashigaofa.client.model.ExchangeRatePutRequest;
import com.zashigaofa.client.model.JObjectApiResult;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for CurrencyApi
 */
@Disabled
public class CurrencyApiTest {

    private final CurrencyApi api = new CurrencyApi();

    
    /**
     * 货币列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void currenciesTest() throws ApiException {
        String appKey = null;
        JObjectApiResult response = 
        api.currencies(appKey);
        
        // TODO: test validations
    }
    
    /**
     * 货币详情
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void currencyTest() throws ApiException {
        Long id = null;
        String appKey = null;
        JObjectApiResult response = 
        api.currency(id, appKey);
        
        // TODO: test validations
    }
    
    /**
     * 删除货币
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void currencyDeleteTest() throws ApiException {
        Long id = null;
        String appKey = null;
        JObjectApiResult response = 
        api.currencyDelete(id, appKey);
        
        // TODO: test validations
    }
    
    /**
     * 删除汇率
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void currencyExchangeRateDeleteTest() throws ApiException {
        Long id = null;
        String appKey = null;
        JObjectApiResult response = 
        api.currencyExchangeRateDelete(id, appKey);
        
        // TODO: test validations
    }
    
    /**
     * 更新汇率
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void currencyExchangeRatePutTest() throws ApiException {
        String code = null;
        String appKey = null;
        ExchangeRatePutRequest exchangeRatePutRequest = null;
        JObjectApiResult response = 
        api.currencyExchangeRatePut(code, appKey, exchangeRatePutRequest);
        
        // TODO: test validations
    }
    
    /**
     * 汇率列表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void currencyExchangeRatesTest() throws ApiException {
        String code = null;
        String appKey = null;
        JObjectApiResult response = 
        api.currencyExchangeRates(code, appKey);
        
        // TODO: test validations
    }
    
    /**
     * 创建货币
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void currencyPostTest() throws ApiException {
        String appKey = null;
        Currency currency = null;
        JObjectApiResult response = 
        api.currencyPost(appKey, currency);
        
        // TODO: test validations
    }
    
    /**
     * 更新货币
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void currencyPutTest() throws ApiException {
        Long id = null;
        String appKey = null;
        Currency currency = null;
        JObjectApiResult response = 
        api.currencyPut(id, appKey, currency);
        
        // TODO: test validations
    }
    
    /**
     * 货币交易记录
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void currencyTransactionsTest() throws ApiException {
        String appKey = null;
        Long userId = null;
        String transType = null;
        String curCode = null;
        OffsetDateTime startTime = null;
        OffsetDateTime endTime = null;
        Integer skip = null;
        Integer take = null;
        JObjectApiResult response = 
        api.currencyTransactions(appKey, userId, transType, curCode, startTime, endTime, skip, take);
        
        // TODO: test validations
    }
    
}
