/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.api;

import com.zashigaofa.client.ApiException;
import com.zashigaofa.client.model.BooleanApiResponse;
import com.zashigaofa.client.model.ServiceGroup;
import com.zashigaofa.client.model.ServiceGroupApiResponse;
import com.zashigaofa.client.model.ServiceGroupListApiResponse;
import com.zashigaofa.client.model.ServiceItem;
import com.zashigaofa.client.model.ServiceItemApiResponse;
import com.zashigaofa.client.model.ServiceItemListApiResponse;
import com.zashigaofa.client.model.ServiceProvider;
import com.zashigaofa.client.model.ServiceProviderApiResponse;
import com.zashigaofa.client.model.ServiceProviderListApiResponse;
import com.zashigaofa.client.model.ServiceSettingGroupPostResultApiResponse;
import com.zashigaofa.client.model.ServiceSettingItemPostResultApiResponse;
import com.zashigaofa.client.model.ServiceSettingProviderPostResultApiResponse;
import com.zashigaofa.client.model.ServiceSettingSettingPostResultApiResponse;
import com.zashigaofa.client.model.Settings;
import com.zashigaofa.client.model.SettingsApiResponse;
import com.zashigaofa.client.model.SettingsListApiResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for ServiceSettingApi
 */
@Disabled
public class ServiceSettingApiTest {

    private final ServiceSettingApi api = new ServiceSettingApi();

    
    /**
     * 获取配置详情
     *
     * 根据配置ID获取配置详情
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingTest() throws ApiException {
        Long id = null;
        SettingsApiResponse response = 
        api.serviceSetting(id);
        
        // TODO: test validations
    }
    
    /**
     * 删除配置
     *
     * 根据配置ID删除配置
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingDeleteTest() throws ApiException {
        Long id = null;
        BooleanApiResponse response = 
        api.serviceSettingDelete(id);
        
        // TODO: test validations
    }
    
    /**
     * 获取服务分组详情
     *
     * 根据服务分组ID获取服务分组详情
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingGroupTest() throws ApiException {
        Long id = null;
        ServiceGroupApiResponse response = 
        api.serviceSettingGroup(id);
        
        // TODO: test validations
    }
    
    /**
     * 删除服务分组
     *
     * 根据服务分组ID删除服务分组
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingGroupDeleteTest() throws ApiException {
        Long id = null;
        BooleanApiResponse response = 
        api.serviceSettingGroupDelete(id);
        
        // TODO: test validations
    }
    
    /**
     * 添加服务分组
     *
     * 添加新的服务分组
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingGroupPostTest() throws ApiException {
        ServiceGroup serviceGroup = null;
        ServiceSettingGroupPostResultApiResponse response = 
        api.serviceSettingGroupPost(serviceGroup);
        
        // TODO: test validations
    }
    
    /**
     * 更新服务分组
     *
     * 根据服务分组ID更新服务分组信息
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingGroupPutTest() throws ApiException {
        Long id = null;
        ServiceGroup serviceGroup = null;
        BooleanApiResponse response = 
        api.serviceSettingGroupPut(id, serviceGroup);
        
        // TODO: test validations
    }
    
    /**
     * 获取服务分组列表
     *
     * 根据服务商ID和显示标志获取服务分组列表
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingGroupsTest() throws ApiException {
        Long providerId = null;
        Boolean showFlag = null;
        ServiceGroupListApiResponse response = 
        api.serviceSettingGroups(providerId, showFlag);
        
        // TODO: test validations
    }
    
    /**
     * 服务配置详情
     *
     * 根据服务配置ID获取服务配置详情
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingItemTest() throws ApiException {
        Long id = null;
        ServiceItemApiResponse response = 
        api.serviceSettingItem(id);
        
        // TODO: test validations
    }
    
    /**
     * 删除服务配置
     *
     * 根据服务配置ID删除服务配置
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingItemDeleteTest() throws ApiException {
        Long id = null;
        BooleanApiResponse response = 
        api.serviceSettingItemDelete(id);
        
        // TODO: test validations
    }
    
    /**
     * 添加服务配置
     *
     * 添加新的服务配置
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingItemPostTest() throws ApiException {
        ServiceItem serviceItem = null;
        ServiceSettingItemPostResultApiResponse response = 
        api.serviceSettingItemPost(serviceItem);
        
        // TODO: test validations
    }
    
    /**
     * 更新服务配置
     *
     * 根据服务配置ID更新服务配置信息
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingItemPutTest() throws ApiException {
        Long id = null;
        ServiceItem serviceItem = null;
        BooleanApiResponse response = 
        api.serviceSettingItemPut(id, serviceItem);
        
        // TODO: test validations
    }
    
    /**
     * 服务配置列表
     *
     * 根据业务代码、服务商代码、分组代码和显示标志获取服务配置列表
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingItemsTest() throws ApiException {
        String bizCode = null;
        String providerCode = null;
        String groupCode = null;
        Boolean showFlag = null;
        ServiceItemListApiResponse response = 
        api.serviceSettingItems(bizCode, providerCode, groupCode, showFlag);
        
        // TODO: test validations
    }
    
    /**
     * 增加配置
     *
     * 添加新的配置
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingPostTest() throws ApiException {
        Settings settings = null;
        ServiceSettingSettingPostResultApiResponse response = 
        api.serviceSettingPost(settings);
        
        // TODO: test validations
    }
    
    /**
     * 获取服务商详情
     *
     * 根据服务商ID获取服务商详情
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingProviderTest() throws ApiException {
        Long id = null;
        ServiceProviderApiResponse response = 
        api.serviceSettingProvider(id);
        
        // TODO: test validations
    }
    
    /**
     * 删除服务商
     *
     * 根据服务商ID删除服务商
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingProviderDeleteTest() throws ApiException {
        Long id = null;
        BooleanApiResponse response = 
        api.serviceSettingProviderDelete(id);
        
        // TODO: test validations
    }
    
    /**
     * 添加服务商
     *
     * 添加新的服务商
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingProviderPostTest() throws ApiException {
        ServiceProvider serviceProvider = null;
        ServiceSettingProviderPostResultApiResponse response = 
        api.serviceSettingProviderPost(serviceProvider);
        
        // TODO: test validations
    }
    
    /**
     * 更新服务商
     *
     * 根据服务商ID更新服务商信息
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingProviderPutTest() throws ApiException {
        Long id = null;
        ServiceProvider serviceProvider = null;
        BooleanApiResponse response = 
        api.serviceSettingProviderPut(id, serviceProvider);
        
        // TODO: test validations
    }
    
    /**
     * 获取服务商列表
     *
     * 根据业务代码和显示标志获取服务商列表
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingProvidersTest() throws ApiException {
        String bizCode = null;
        Boolean showFlag = null;
        ServiceProviderListApiResponse response = 
        api.serviceSettingProviders(bizCode, showFlag);
        
        // TODO: test validations
    }
    
    /**
     * 更新配置
     *
     * 根据配置ID更新配置信息
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingPutTest() throws ApiException {
        Long id = null;
        Settings settings = null;
        BooleanApiResponse response = 
        api.serviceSettingPut(id, settings);
        
        // TODO: test validations
    }
    
    /**
     * 获取配置列表
     *
     * 根据业务代码、业务标识、服务商代码、分组代码、标签和配置项代码获取配置列表
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void serviceSettingsTest() throws ApiException {
        String bizCode = null;
        String bizId = null;
        String providerCode = null;
        String groupCode = null;
        String tag = null;
        String code = null;
        SettingsListApiResponse response = 
        api.serviceSettings(bizCode, bizId, providerCode, groupCode, tag, code);
        
        // TODO: test validations
    }
    
}
