/*
 * 全部  API 文档
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.zashigaofa.client.api;

import com.zashigaofa.client.ApiException;
import com.zashigaofa.client.model.ExecuteFunctionRequest;
import java.io.File;
import com.zashigaofa.client.model.JObjectApiResult;
import java.time.OffsetDateTime;
import com.zashigaofa.client.model.PostIndexRequest;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;


/**
 * API tests for StorageApi
 */
@Disabled
public class StorageApiTest {

    private final StorageApi api = new StorageApi();

    
    /**
     * 聚合查询
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageAggregateTest() throws ApiException {
        String table = null;
        String appKey = null;
        String pipeline = null;
        JObjectApiResult response = 
        api.storageAggregate(table, appKey, pipeline);
        
        // TODO: test validations
    }
    
    /**
     * 清空表数据
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageClearTest() throws ApiException {
        String table = null;
        String appKey = null;
        String filter = null;
        JObjectApiResult response = 
        api.storageClear(table, appKey, filter);
        
        // TODO: test validations
    }
    
    /**
     * 删除数据
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageDeleteTest() throws ApiException {
        String table = null;
        String id = null;
        String appKey = null;
        JObjectApiResult response = 
        api.storageDelete(table, id, appKey);
        
        // TODO: test validations
    }
    
    /**
     * 删除索引
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageDeleteIndexTest() throws ApiException {
        String table = null;
        String appKey = null;
        String indexName = null;
        JObjectApiResult response = 
        api.storageDeleteIndex(table, appKey, indexName);
        
        // TODO: test validations
    }
    
    /**
     * 数据详情
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageDetailTest() throws ApiException {
        String table = null;
        String id = null;
        String appKey = null;
        String project = null;
        JObjectApiResult response = 
        api.storageDetail(table, id, appKey, project);
        
        // TODO: test validations
    }
    
    /**
     * 执行函数
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageExecuteFunctionTest() throws ApiException {
        String nonce = null;
        Long timestamp = null;
        String signature = null;
        String appKey = null;
        ExecuteFunctionRequest executeFunctionRequest = null;
        JObjectApiResult response = 
        api.storageExecuteFunction(nonce, timestamp, signature, appKey, executeFunctionRequest);
        
        // TODO: test validations
    }
    
    /**
     * 导出数据
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageExportTest() throws ApiException {
        String table = null;
        String appKey = null;
        String filter = null;
        OffsetDateTime startTime = null;
        OffsetDateTime endTime = null;
        File response = 
        api.storageExport(table, appKey, filter, startTime, endTime);
        
        // TODO: test validations
    }
    
    /**
     * 导入数据
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageImportTest() throws ApiException {
        String table = null;
        String appKey = null;
        File _file = null;
        JObjectApiResult response = 
        api.storageImport(table, appKey, _file);
        
        // TODO: test validations
    }
    
    /**
     * 获取索引
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageIndexesTest() throws ApiException {
        String table = null;
        String appKey = null;
        JObjectApiResult response = 
        api.storageIndexes(table, appKey);
        
        // TODO: test validations
    }
    
    /**
     * 查询数据
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageListTest() throws ApiException {
        String table = null;
        String appKey = null;
        String filter = null;
        String project = null;
        String sort = null;
        OffsetDateTime startTime = null;
        OffsetDateTime endTime = null;
        Boolean explain = null;
        Integer take = null;
        Integer skip = null;
        JObjectApiResult response = 
        api.storageList(table, appKey, filter, project, sort, startTime, endTime, explain, take, skip);
        
        // TODO: test validations
    }
    
    /**
     * 添加数据
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storagePostTest() throws ApiException {
        String table = null;
        String appKey = null;
        List<Object> requestBody = null;
        JObjectApiResult response = 
        api.storagePost(table, appKey, requestBody);
        
        // TODO: test validations
    }
    
    /**
     * 添加索引
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storagePostIndexTest() throws ApiException {
        String table = null;
        String appKey = null;
        PostIndexRequest postIndexRequest = null;
        JObjectApiResult response = 
        api.storagePostIndex(table, appKey, postIndexRequest);
        
        // TODO: test validations
    }
    
    /**
     * 更新数据
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storagePutTest() throws ApiException {
        String table = null;
        String id = null;
        String appKey = null;
        Object body = null;
        Boolean replace = null;
        JObjectApiResult response = 
        api.storagePut(table, id, appKey, body, replace);
        
        // TODO: test validations
    }
    
    /**
     * 删除表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageRemoveTest() throws ApiException {
        String table = null;
        String appKey = null;
        JObjectApiResult response = 
        api.storageRemove(table, appKey);
        
        // TODO: test validations
    }
    
    /**
     * 数据表统计
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageStatsTest() throws ApiException {
        String table = null;
        String appKey = null;
        JObjectApiResult response = 
        api.storageStats(table, appKey);
        
        // TODO: test validations
    }
    
    /**
     * 获取数据表
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storageTablesTest() throws ApiException {
        String appKey = null;
        JObjectApiResult response = 
        api.storageTables(appKey);
        
        // TODO: test validations
    }
    
}
